import type {Metadata} from "next";
import Link from "next/link";
import {listContributionRecords} from "@/lib/firebase/contribution-admin";
import {listDeletionRequests} from "@/lib/firebase/asset-admin";
import {resolveCrmSession} from "@/lib/firebase/session";
export const metadata:Metadata={title:"Administration communautaire",robots:{index:false,follow:false}};
const domains=["Contributions","Relecture","Organisations","Fichiers privés","Journal d’audit"],editorial=["draft.self.manage","review.assigned.read","review.assigned.comment","editorial.assign","editorial.completeness.review","editorial.provenance.verify","editorial.rights.verify","editorial.consent.verify","editorial.ordinary.approve"],assets=["asset.self.manage","asset.assigned.read","asset.assigned.review","asset.deletion.manage"];
const labels:Record<string,string>={draft:"Brouillon",submitted:"À affecter",rights_review:"Contrôles documentaires",editorial_review:"Relecture éditoriale",approved:"Prêt à publier",published:"Publié",changes_requested:"Corrections demandées",rejected:"Refusé",unpublished:"Dépublié"},actionStatuses=new Set(["submitted","rights_review","editorial_review","approved","changes_requested"]);
export default async function CrmPage(){
 const context=await resolveCrmSession(),permissions=context.state==="authorized"?context.permissions:[],hasEditorial=permissions.some(p=>editorial.includes(p)),hasAssets=permissions.some(p=>assets.includes(p)),hasAudit=permissions.includes("audit.read");
 const [editorialData,deletionData]=await Promise.all([hasEditorial&&context.state==="authorized"?listContributionRecords(context.uid,{limit:"100"}).catch(()=>({contributions:[],nextCursor:null})):Promise.resolve({contributions:[],nextCursor:null}),permissions.includes("asset.deletion.manage")&&context.state==="authorized"?listDeletionRequests(context.uid,{limit:"25"}).catch(()=>({requests:[],nextCursor:null})):Promise.resolve({requests:[],nextCursor:null})]);
 const contributions=editorialData.contributions,attention=contributions.filter(item=>actionStatuses.has(item.status)),published=contributions.filter(item=>item.status==="published"),recent=contributions.slice(0,4);
 const tools=[hasEditorial&&{href:"/crm/contributions",index:"01",title:"Contributions",text:"Recevoir, documenter et accompagner chaque récit jusqu’à sa publication.",meta:"Circuit éditorial"},hasAssets&&{href:"/crm/fichiers",index:"02",title:"Fonds documentaires",text:"Préserver les originaux, leurs droits, leur provenance et leur consentement.",meta:"Archives privées"},permissions.includes("profile.assigned.read")&&{href:"/crm/comptes",index:"03",title:"Comptes & rôles",text:"Administrer les accès nominatifs et les responsabilités avec précision.",meta:"Gouvernance"},permissions.some(p=>["organization.list","organization.member.manage","role.local.manage"].includes(p))&&{href:"/crm/organisations",index:"04",title:"Organisations",text:"Relier comité, associations et structures au sein d’un même espace.",meta:"Vie collective"},hasAudit&&{href:"/crm/journal",index:"05",title:"Journal d’audit",text:"Retrouver chaque action sensible dans une chronologie non modifiable.",meta:"Traçabilité"}].filter(Boolean) as Array<{href:string;index:string;title:string;text:string;meta:string}>;
 const future=domains.filter(domain=>domain!=="Organisations"&&(!hasAssets||domain!=="Fichiers privés")&&(!hasEditorial||!["Contributions","Relecture"].includes(domain))&&(!hasAudit||domain!=="Journal d’audit"));
 return <main className="crm-shell crm-dashboard"><header className="crm-dashboard-hero"><div><p className="crm-kicker">Tableau de bord</p><h1>La mémoire du village,<br/><em>organisée avec soin.</em></h1><p>Bienvenue, <strong>{context.state==="authorized"?context.displayName:"membre autorisé"}</strong>. Cet espace réunit les outils nécessaires pour recueillir, vérifier et transmettre les contributions d’Aït Mesbah.</p></div><div className="crm-dashboard-seal" aria-hidden="true"><span>ⵣ</span><small>Administration<br/>communautaire</small></div></header><section className="crm-dashboard-intro" aria-labelledby="active-domain"><div><span>Outils autorisés</span><strong>{String(tools.length).padStart(2,"0")}</strong></div><div><span>Cadre</span><strong>Privé & sécurisé</strong></div><p id="active-domain">Chaque action importante est nominative, motivée et inscrite dans le journal du CRM.</p></section>
 {hasEditorial&&<section className="crm-command-center" aria-labelledby="command-title"><div className="crm-section-heading"><p className="crm-kicker">Vue opérationnelle</p><h2 id="command-title">À traiter maintenant</h2></div><div className="crm-command-grid"><div className="crm-command-metrics"><Link href="/crm/contributions"><span>Dossiers accessibles</span><strong>{String(contributions.length).padStart(2,"0")}</strong><small>dans cette vue bornée</small></Link><Link href="/crm/contributions"><span>Attention requise</span><strong>{String(attention.length).padStart(2,"0")}</strong><small>à relire ou décider</small></Link><Link href="/crm/contributions?status=published"><span>Transmis au public</span><strong>{String(published.length).padStart(2,"0")}</strong><small>publications actives</small></Link><Link href="/crm/fichiers"><span>Suppressions</span><strong>{String(deletionData.requests.length).padStart(2,"0")}</strong><small>à examiner</small></Link></div><div className="crm-priority-list"><header><div><p className="crm-kicker">File prioritaire</p><h3>Les prochains gestes utiles</h3></div><Link href="/crm/contributions">Voir tous les dossiers →</Link></header>{attention.length?<ol>{attention.slice(0,4).map(item=><li key={item.contributionId}><span data-status={item.status}>{labels[item.status]??item.status}</span><div><strong>{item.title}</strong><small>Version {item.currentVersion} · {item.category.replaceAll("_"," ")}</small></div><Link href={`/crm/contributions?titlePrefix=${encodeURIComponent(item.title.slice(0,40))}`} aria-label={`Ouvrir ${item.title}`}>→</Link></li>)}</ol>:<div className="crm-priority-empty"><span>✓</span><div><strong>La file est à jour</strong><p>Aucun dossier accessible ne réclame de décision immédiate.</p></div></div>}</div></div>{recent.length>0&&<div className="crm-recent-strip"><span>Derniers dossiers accessibles</span>{recent.map(item=><Link href={`/crm/contributions?titlePrefix=${encodeURIComponent(item.title.slice(0,40))}`} key={item.contributionId}><strong>{item.title}</strong><small>{labels[item.status]??item.status}</small></Link>)}</div>}</section>}
 <section className="crm-tool-section"><div className="crm-section-heading"><p className="crm-kicker">Votre espace de travail</p><h2>Que souhaitez-vous faire&nbsp;?</h2></div><div className="crm-tool-grid">{tools.map(tool=><Link className="crm-tool-card" href={tool.href} key={tool.href}><span className="crm-tool-index">{tool.index}</span><small>{tool.meta}</small><strong>{tool.title}</strong><p>{tool.text}</p><i>Ouvrir l’espace <b>→</b></i></Link>)}</div></section><section className="crm-dashboard-principle"><p className="crm-kicker">Principe éditorial</p><blockquote>«&nbsp;Préserver sans figer,<br/>transmettre sans déformer.&nbsp;»</blockquote><p>Le CRM accompagne le travail humain. Il rend les décisions lisibles, mais ne remplace ni le dialogue, ni la connaissance du village.</p></section>{future.length>0&&<section aria-labelledby="future-domains"><h2 id="future-domains">Domaines à venir</h2><ul className="crm-domain-list">{future.map((domain,index)=><li key={domain}><span>{String(index+1).padStart(2,"0")}</span><strong>{domain}</strong><small>En préparation</small></li>)}</ul></section>}</main>;
}
