import "server-only";
import { FieldPath, Timestamp } from "firebase-admin/firestore";
import { getLocalFirebaseAdmin } from "./admin";
import { createInvitedProfile } from "@/lib/crm/account-lifecycle.mjs";
import { normalizeLegacyAudit } from "@/lib/crm/audit-log.mjs";
import { authorizeAccountOperation as rawAuthorize, parseAccountQuery as rawParse, prepareInvitationInput, prepareRoleChange, prepareStatusChange, serializeAccount as rawSerialize } from "@/lib/crm/account-management.mjs";
import { rejectInexactFilters } from "@/lib/crm/request-security.mjs";
import { assertSessionVersion,nextSessionVersion } from "@/lib/crm/session-policy.mjs";

type Actor={uid:string;permissions:readonly string[];status:"active"};
type AccountQuery={limit:number;cursor?:string;status?:string;role?:string;prefix?:string};
const authorizeAccountOperation=rawAuthorize as (input:{actor:Actor;target?:FirebaseFirestore.DocumentData;permission:string;operation?:string;nextRole?:string})=>boolean;
const parseAccountQuery=rawParse as (input:Record<string,string|undefined>)=>AccountQuery;
const serializeAccount=rawSerialize as (profile:FirebaseFirestore.DocumentData,options?:{showEmail?:boolean;authDisabled?:boolean|null})=>Record<string,unknown>;
function auditRef(database:FirebaseFirestore.Firestore,event:Record<string,unknown>){const ref=database.collection("auditLogs").doc();return {ref,value:normalizeLegacyAudit(event,{eventId:ref.id,correlationId:database.collection("correlations").doc().id} as never)};}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character]!));}
async function accountSetupMessage(auth:ReturnType<typeof getLocalFirebaseAdmin>["auth"],email:string,displayName:string,canonicalUrl:string){const continueUrl=`${canonicalUrl}/connexion`;const [passwordUrl,verificationUrl]=await Promise.all([auth.generatePasswordResetLink(email,{url:continueUrl}),auth.generateEmailVerificationLink(email,{url:continueUrl})]);const safeName=escapeHtml(displayName);return {passwordUrl,verificationUrl,message:{subject:"Votre accès à la maison éditoriale d’Aït Mesbah",text:`Bonjour ${displayName},\n\nUn accès à la maison éditoriale d’Aït Mesbah vient d’être préparé pour vous.\n\n1. Définissez votre mot de passe : ${passwordUrl}\n2. Vérifiez votre adresse électronique : ${verificationUrl}\n3. Connectez-vous au CRM : ${continueUrl}\n\nCes liens sont personnels et ne doivent pas être transférés.\n\nAït Mesbah — Village & Mémoire`,html:`<div style="font-family:Georgia,serif;color:#173e32;line-height:1.65;max-width:620px;margin:auto"><p style="color:#a85d3b;font:700 12px Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase">Aït Mesbah · Village &amp; Mémoire</p><h1 style="font-size:30px;line-height:1.15;font-weight:500">Bienvenue dans la maison éditoriale</h1><p>Bonjour ${safeName},</p><p>Un accès au CRM d’Aït Mesbah vient d’être préparé pour vous. Pour le sécuriser, suivez ces deux étapes dans l’ordre.</p><p style="margin:28px 0"><a href="${passwordUrl}" style="display:inline-block;background:#173e32;color:#fff;padding:14px 20px;text-decoration:none;font:700 12px Arial,sans-serif;letter-spacing:.06em">1 · DÉFINIR MON MOT DE PASSE</a></p><p style="margin:28px 0"><a href="${verificationUrl}" style="display:inline-block;border:1px solid #173e32;color:#173e32;padding:13px 20px;text-decoration:none;font:700 12px Arial,sans-serif;letter-spacing:.06em">2 · VÉRIFIER MON ADRESSE</a></p><p>Vous pourrez ensuite vous connecter sur <a href="${continueUrl}" style="color:#a85d3b">ait-mesbah.org</a>.</p><p style="font:13px Arial,sans-serif;color:#6d756f">Ces liens sont personnels. Ne les transférez à personne.</p></div>`}};}
async function queueAccountSetupEmail(database:FirebaseFirestore.Firestore,auth:ReturnType<typeof getLocalFirebaseAdmin>["auth"],profile:FirebaseFirestore.DocumentData,canonicalUrl:string,actorUid:string,batch?:FirebaseFirestore.WriteBatch){const links=await accountSetupMessage(auth,profile.email,profile.displayName,canonicalUrl);const ref=database.collection("crmMailQueue").doc(),document={to:[profile.email],message:links.message,category:"account_invitation",targetUid:profile.uid,requestedBy:actorUid,createdAt:Timestamp.now()};if(batch)batch.create(ref,document);else await ref.create(document);return {queueId:ref.id,...links};}

export async function listAccounts(actor:Actor,raw:Record<string,string|undefined>){authorizeAccountOperation({actor,permission:"profile.assigned.read"});rejectInexactFilters(raw);const input=parseAccountQuery(Object.fromEntries(Object.entries(raw).filter(([,v])=>v!=null&&v!=="")));const {auth,database}=getLocalFirebaseAdmin();let query:FirebaseFirestore.Query=database.collection("users").orderBy(FieldPath.documentId()).limit(input.limit+1);if(input.cursor)query=query.startAfter(input.cursor);const snapshot=await query.get(),page=snapshot.docs.slice(0,input.limit);const users=page.length?await auth.getUsers(page.map(doc=>({uid:doc.id}))):{users:[]};const identities=new Map(users.users.map(user=>[user.uid,user]));return {accounts:page.map(doc=>serializeAccount(doc.data(),{showEmail:true,authDisabled:identities.get(doc.id)?.disabled??null})),nextCursor:snapshot.size>input.limit?snapshot.docs[input.limit-1].id:null};}

export async function inviteAccount(actor:Actor,input:unknown){authorizeAccountOperation({actor,permission:"member.approve"});const clean=prepareInvitationInput(input as {displayName:string;email:string});const {auth,database,config}=getLocalFirebaseAdmin();const identity=await auth.createUser({email:clean.email,displayName:clean.displayName,disabled:true,emailVerified:false});try{const now=Timestamp.now();const profile=createInvitedProfile({uid:identity.uid,...clean,actorUid:actor.uid,now});const event=auditRef(database,{action:"account.invited",actorUid:actor.uid,targetUid:identity.uid,previousStatus:null,nextStatus:"invited",occurredAt:now,profileVersion:1});const batch=database.batch(),canonicalUrl="canonicalUrl" in config?config.canonicalUrl:"http://localhost:3100";batch.create(database.doc(`users/${identity.uid}`),profile);batch.create(event.ref,event.value);const delivery=await queueAccountSetupEmail(database,auth,profile,canonicalUrl,actor.uid,batch);await batch.commit();return {...serializeAccount(profile,{showEmail:true,authDisabled:true}),invitation:{state:"queued",queueId:delivery.queueId}};}catch(error){await auth.deleteUser(identity.uid).catch(()=>{});throw error;}}

export async function createAccountSetupLinks(actor:Actor,uid:string){authorizeAccountOperation({actor,permission:"member.approve"});const {auth,database,config}=getLocalFirebaseAdmin();const snapshot=await database.doc(`users/${uid}`).get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;authorizeAccountOperation({actor,target:profile,permission:"member.approve"});if(profile.status!=="invited"||profile.globalRoles.length!==0)throw Object.assign(new Error("compte non éligible"),{http:409});const identity=await auth.getUser(uid);if(!identity.email||identity.email.trim().toLowerCase()!==profile.email||identity.emailVerified)throw Object.assign(new Error("identité non éligible"),{http:409});const canonicalUrl="canonicalUrl" in config?config.canonicalUrl:"http://localhost:3100",continueUrl=`${canonicalUrl}/connexion`;const [passwordUrl,verificationUrl]=await Promise.all([auth.generatePasswordResetLink(identity.email,{url:continueUrl}),auth.generateEmailVerificationLink(identity.email,{url:continueUrl})]);return {passwordUrl,verificationUrl,expiresNotice:"Liens Firebase à usage unique. Transmettez-les uniquement au titulaire."};}

export async function sendAccountSetupEmail(actor:Actor,uid:string){authorizeAccountOperation({actor,permission:"member.approve"});const {auth,database,config}=getLocalFirebaseAdmin();const snapshot=await database.doc(`users/${uid}`).get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;authorizeAccountOperation({actor,target:profile,permission:"member.approve"});if(profile.status!=="invited"||profile.globalRoles.length!==0)throw Object.assign(new Error("compte non éligible"),{http:409});const identity=await auth.getUser(uid);if(!identity.email||identity.email.trim().toLowerCase()!==profile.email||identity.emailVerified)throw Object.assign(new Error("identité non éligible"),{http:409});const canonicalUrl="canonicalUrl" in config?config.canonicalUrl:"http://localhost:3100";const delivery=await queueAccountSetupEmail(database,auth,profile,canonicalUrl,actor.uid);return {state:"queued",queueId:delivery.queueId,message:"L’invitation a été confiée au service d’envoi."};}

export async function changeAccountStatus(actor:Actor,uid:string,input:{status:string;reason:string;expectedVersion:number}){const permission=input.status==="active"?"member.approve":"member.suspend";const {auth,database}=getLocalFirebaseAdmin();const ref=database.doc(`users/${uid}`),snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;assertSessionVersion(profile.version,{incrementable:true});authorizeAccountOperation({actor,target:profile,permission});const result=prepareStatusChange(profile,input.status,{actorUid:actor.uid,reason:input.reason,now:Timestamp.now(),expectedVersion:input.expectedVersion});let previousIdentity:Awaited<ReturnType<typeof auth.getUser>>|null=null;try{previousIdentity=await auth.getUser(uid);}catch(error){const code=(error as {code?:string}).code;if(code!=="auth/user-not-found"||input.status!=="revoked")throw error;}if(previousIdentity)await auth.updateUser(uid,{disabled:input.status!=="active"});try{await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");assertSessionVersion(fresh.data()!.version,{incrementable:true});if(result.profile.version!==nextSessionVersion(fresh.data()!.version))throw new Error("version de session incohérente");const event=auditRef(database,result.auditEvent);tx.set(ref,result.profile);tx.create(event.ref,event.value);});}catch(error){if(previousIdentity)await auth.updateUser(uid,{disabled:previousIdentity.disabled}).catch(()=>{});throw error;}if(previousIdentity&&input.status!=="active")await auth.revokeRefreshTokens(uid);return serializeAccount(result.profile,{showEmail:true,authDisabled:previousIdentity?input.status!=="active":null});}

export async function changeAccountRoles(actor:Actor,uid:string,input:{roles:string[];reason:string;expectedVersion:number}){const {auth,database}=getLocalFirebaseAdmin();const ref=database.doc(`users/${uid}`),snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;assertSessionVersion(profile.version,{incrementable:true});authorizeAccountOperation({actor,target:profile,permission:"role.global.manage",nextRole:input.roles.find(role=>["administrator","technical_owner"].includes(role))});const result=prepareRoleChange(profile,input.roles,{actorUid:actor.uid,reason:input.reason,now:Timestamp.now(),expectedVersion:input.expectedVersion});await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");assertSessionVersion(fresh.data()!.version,{incrementable:true});if(result.profile.version!==nextSessionVersion(fresh.data()!.version))throw new Error("version de session incohérente");const event=auditRef(database,result.auditEvent);tx.set(ref,result.profile);tx.create(event.ref,event.value);});await auth.revokeRefreshTokens(uid);return serializeAccount(result.profile,{showEmail:true});}
