import "server-only";
import { FieldPath, Timestamp } from "firebase-admin/firestore";
import { getLocalFirebaseAdmin } from "./admin";
import { createInvitedProfile } from "@/lib/crm/account-lifecycle.mjs";
import { normalizeLegacyAudit } from "@/lib/crm/audit-log.mjs";
import { authorizeAccountOperation as rawAuthorize, parseAccountQuery as rawParse, prepareInvitationInput, prepareRoleChange, prepareStatusChange, serializeAccount as rawSerialize } from "@/lib/crm/account-management.mjs";

type Actor={uid:string;permissions:readonly string[];status:"active"};
type AccountQuery={limit:number;cursor?:string;status?:string;role?:string;prefix?:string};
const authorizeAccountOperation=rawAuthorize as (input:{actor:Actor;target?:FirebaseFirestore.DocumentData;permission:string;operation?:string;nextRole?:string})=>boolean;
const parseAccountQuery=rawParse as (input:Record<string,string|undefined>)=>AccountQuery;
const serializeAccount=rawSerialize as (profile:FirebaseFirestore.DocumentData,options?:{showEmail?:boolean;authDisabled?:boolean|null})=>Record<string,unknown>;
function auditRef(database:FirebaseFirestore.Firestore,event:Record<string,unknown>){const ref=database.collection("auditLogs").doc();return {ref,value:normalizeLegacyAudit(event,{eventId:ref.id,correlationId:database.collection("correlations").doc().id} as never)};}

export async function listAccounts(actor:Actor,raw:Record<string,string|undefined>){authorizeAccountOperation({actor,permission:"profile.assigned.read"});const input=parseAccountQuery(Object.fromEntries(Object.entries(raw).filter(([,v])=>v!=null&&v!=="")));const {auth,database}=getLocalFirebaseAdmin();let query:FirebaseFirestore.Query=database.collection("users").orderBy(FieldPath.documentId()).limit(input.limit+1);if(input.cursor)query=query.startAfter(input.cursor);const snapshot=await query.get();let docs=snapshot.docs;if(input.status)docs=docs.filter(doc=>doc.data().status===input.status);if(input.role)docs=docs.filter(doc=>doc.data().globalRoles?.includes(input.role));if(input.prefix){const prefix=input.prefix.toLocaleLowerCase("fr");docs=docs.filter(doc=>doc.data().displayName?.toLocaleLowerCase("fr").startsWith(prefix));}const page=docs.slice(0,input.limit);const users=page.length?await auth.getUsers(page.map(doc=>({uid:doc.id}))):{users:[]};const identities=new Map(users.users.map(user=>[user.uid,user]));return {accounts:page.map(doc=>serializeAccount(doc.data(),{showEmail:true,authDisabled:identities.get(doc.id)?.disabled??null})),nextCursor:snapshot.size>input.limit?snapshot.docs[input.limit-1].id:null};}

export async function inviteAccount(actor:Actor,input:unknown){authorizeAccountOperation({actor,permission:"member.approve"});const clean=prepareInvitationInput(input as {displayName:string;email:string});const {auth,database}=getLocalFirebaseAdmin();const identity=await auth.createUser({email:clean.email,displayName:clean.displayName,disabled:true,emailVerified:false});try{const now=Timestamp.now();const profile=createInvitedProfile({uid:identity.uid,...clean,actorUid:actor.uid,now});const event=auditRef(database,{action:"account.invited",actorUid:actor.uid,targetUid:identity.uid,previousStatus:null,nextStatus:"invited",occurredAt:now,profileVersion:1});const batch=database.batch();batch.create(database.doc(`users/${identity.uid}`),profile);batch.create(event.ref,event.value);await batch.commit();return serializeAccount(profile,{showEmail:true,authDisabled:true});}catch(error){await auth.deleteUser(identity.uid).catch(()=>{});throw error;}}

export async function changeAccountStatus(actor:Actor,uid:string,input:{status:string;reason:string;expectedVersion:number}){const permission=input.status==="active"?"member.approve":"member.suspend";const {auth,database}=getLocalFirebaseAdmin();const ref=database.doc(`users/${uid}`),snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;authorizeAccountOperation({actor,target:profile,permission});const result=prepareStatusChange(profile,input.status,{actorUid:actor.uid,reason:input.reason,now:Timestamp.now(),expectedVersion:input.expectedVersion});const previousIdentity=await auth.getUser(uid);await auth.updateUser(uid,{disabled:input.status!=="active"});try{await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");const event=auditRef(database,result.auditEvent);tx.set(ref,result.profile);tx.create(event.ref,event.value);});}catch(error){await auth.updateUser(uid,{disabled:previousIdentity.disabled}).catch(()=>{});throw error;}if(input.status!=="active")await auth.revokeRefreshTokens(uid);return serializeAccount(result.profile,{showEmail:true,authDisabled:input.status!=="active"});}

export async function changeAccountRoles(actor:Actor,uid:string,input:{roles:string[];reason:string;expectedVersion:number}){const {database}=getLocalFirebaseAdmin();const ref=database.doc(`users/${uid}`),snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{code:404});const profile=snapshot.data()!;authorizeAccountOperation({actor,target:profile,permission:"role.global.manage",nextRole:input.roles.find(role=>["administrator","technical_owner"].includes(role))});const result=prepareRoleChange(profile,input.roles,{actorUid:actor.uid,reason:input.reason,now:Timestamp.now(),expectedVersion:input.expectedVersion});await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");const event=auditRef(database,result.auditEvent);tx.set(ref,result.profile);tx.create(event.ref,event.value);});return serializeAccount(result.profile,{showEmail:true});}
