import { transitionActivation } from "../crm/activation-policy.mjs";
import { createActivationContinuation,verifyActivationContinuation } from "../crm/activation-continuation.mjs";
import { assertProfile } from "../crm/account-lifecycle.mjs";
import { activationRecordToFirestore,validateExactRawActivation } from "./invitation-admin.mjs";

const generic=()=>{throw Object.assign(new Error("activation impossible"),{code:"ACTIVATION_REJECTED"});};
function verifiedContinuation(token,options){try{return verifyActivationContinuation(token,options);}catch{generic();}}
function profileIsEligible(raw,claims,identity){try{assertProfile(raw);}catch{generic();}if(raw.uid!==claims.uid||raw.status!=="invited"||raw.globalRoles.length!==0||raw.email!==identity.email?.trim().toLowerCase())generic();return raw;}
function continuation(claims,{secret,environment,nowMs,limitMs}){const expiresAt=Math.min(nowMs+15*60*1000,limitMs);if(expiresAt<=nowMs)generic();return createActivationContinuation({...claims,environment,issuedAt:nowMs,expiresAt},{secret,nowMs});}
async function authoritativeState(database,auth,claims,expectedState,nowMs){const [activationSnapshot,profileSnapshot,identity]=await Promise.all([database.doc(`crmActivations/${claims.activationId}`).get(),database.doc(`users/${claims.uid}`).get(),auth.getUser(claims.uid)]);if(!activationSnapshot.exists||!profileSnapshot.exists)generic();const activation=validateExactRawActivation(activationSnapshot.data());if(activation.activationId!==claims.activationId||activation.uid!==claims.uid||activation.version!==claims.version||activation.state!==expectedState||nowMs>=activation.expiresAt||identity.uid!==claims.uid)generic();profileIsEligible(profileSnapshot.data(),claims,identity);return {activation,identity};}
export async function enableLocalActivationIdentity(auth,uid){const identity=await auth.getUser(uid);if(identity.uid!==uid||identity.emailVerified!==false)generic();await auth.revokeRefreshTokens(uid);if(identity.disabled)await auth.updateUser(uid,{disabled:false});const enabled=await auth.getUser(uid);if(enabled.disabled||enabled.emailVerified)generic();return enabled;}
export async function beginLocalActivation(database,auth,result,{secret,environment,nowMs,activateIdentity=enableLocalActivationIdentity}){if(environment!=="local"||result.state!=="accepted")generic();const claims={activationId:result.activationId,uid:result.uid,version:result.version},loaded=await authoritativeState(database,auth,claims,"password_pending",nowMs);if(loaded.identity.email!==result.email||loaded.identity.emailVerified)generic();const token=continuation({...claims,state:"password_pending"},{secret,environment,nowMs,limitMs:loaded.activation.expiresAt});try{await activateIdentity(auth,result.uid);await auth.generatePasswordResetLink(result.email);return Object.freeze({continuation:token,ready:true});}catch{return Object.freeze({continuation:token,ready:false});}}
export async function resumeLocalActivationIdentity(database,auth,token,{secret,environment,nowMs,activateIdentity=enableLocalActivationIdentity}){const claims=verifiedContinuation(token,{secret,environment,expectedState:"password_pending",nowMs}),loaded=await authoritativeState(database,auth,claims,"password_pending",nowMs),identity=await activateIdentity(auth,claims.uid);if(identity.email!==loaded.identity.email)generic();await auth.generatePasswordResetLink(identity.email);return Object.freeze({continuation:token,ready:true});}
async function reconcile(database,auth,token,idToken,{secret,environment,nowMs,expectedState,nextState,beforeTransaction,beforeWrite}){const claims=verifiedContinuation(token,{secret,environment,expectedState,nowMs});if(typeof idToken!=="string"||idToken.length<32||idToken.length>8192)generic();const decoded=await auth.verifyIdToken(idToken,true);if(decoded.uid!==claims.uid||!Number.isFinite(decoded.auth_time)||nowMs-decoded.auth_time*1000<0||nowMs-decoded.auth_time*1000>5*60*1000)generic();const identity=await auth.getUser(claims.uid);if(identity.disabled||identity.uid!==claims.uid||identity.email?.trim().toLowerCase()!==decoded.email?.trim().toLowerCase())generic();if(nextState==="mfa_enrollment_pending"&&identity.emailVerified!==true)generic();if(beforeTransaction)await beforeTransaction();return database.runTransaction(async tx=>{const activationRef=database.doc(`crmActivations/${claims.activationId}`),profileRef=database.doc(`users/${claims.uid}`),[activationSnapshot,profileSnapshot]=await Promise.all([tx.get(activationRef),tx.get(profileRef)]);if(!activationSnapshot.exists||!profileSnapshot.exists)generic();const activation=validateExactRawActivation(activationSnapshot.data());profileIsEligible(profileSnapshot.data(),claims,identity);if(activation.activationId!==claims.activationId||activation.uid!==claims.uid||nowMs>=activation.expiresAt)generic();if(activation.state===nextState&&activation.version===claims.version+1)return {activation,idempotent:true,identity};if(activation.state!==expectedState||activation.version!==claims.version)generic();if(beforeWrite)await beforeWrite();const updated=transitionActivation(activation,nextState,{now:nowMs,serverProof:true});tx.set(activationRef,activationRecordToFirestore(updated));return {activation:updated,idempotent:false,identity};});}
export async function reconcileLocalActivationPassword(database,auth,token,idToken,options){const result=await reconcile(database,auth,token,idToken,{...options,expectedState:"password_pending",nextState:"email_verification_pending"});await auth.generateEmailVerificationLink(result.identity.email);return Object.freeze({state:"email_verification_pending",continuation:continuation({activationId:result.activation.activationId,uid:result.activation.uid,version:result.activation.version,state:"email_verification_pending"},{...options,limitMs:result.activation.expiresAt})});}
export async function reconcileLocalActivationEmail(database,auth,token,idToken,options){await reconcile(database,auth,token,idToken,{...options,expectedState:"email_verification_pending",nextState:"mfa_enrollment_pending"});return Object.freeze({state:"mfa_enrollment_pending"});}
