import "server-only";
import {randomBytes} from "node:crypto";
import {FieldPath,Timestamp} from "firebase-admin/firestore";
import {getLocalFirebaseAdmin} from "./admin";
import {normalizeLegacyAudit} from "@/lib/crm/audit-log.mjs";
import {createDraft,recordDecision} from "@/lib/crm/editorial-workflow.mjs";
import {documentaryPermission,assertOrdinaryApproval,minimalContribution,parseContributionQuery,prepareDraftInput,prepareVersion,requireAssigned,requireAuthor} from "@/lib/crm/contribution-management.mjs";
import {effectivePermissions} from "@/lib/crm/organization-authorization.mjs";
import {loadAuthoritativeMemberships} from "./membership-quota-admin";
import {rejectInexactFilters} from "@/lib/crm/request-security.mjs";
import {preparePublicEventPublication,preparePublicEventUnpublication,preparePublicEventUpdate} from "@/lib/crm/public-event-publication.mjs";
import {preparePublicContentPublication,preparePublicContentUnpublication} from "@/lib/crm/public-content-publication.mjs";
import {prepareEditorialMetadata} from "@/lib/crm/editorial-metadata.mjs";

type Actor={uid:string;status:"active";globalPermissions:string[];organizationIds:string[]};
async function actorContext(uid:string):Promise<Actor>{const {database}=getLocalFirebaseAdmin(),profile=await database.doc(`users/${uid}`).get();if(!profile.exists||profile.data()!.status!=="active")throw Object.assign(new Error("acteur inactif"),{http:403});const data=profile.data()!,globalPermissions=effectivePermissions({accountStatus:data.status,globalRoles:data.globalRoles,organization:null,membership:null,organizationId:null}).global,organizationIds:string[]=[];for(const membership of await loadAuthoritativeMemberships(database,uid)){const organization=await database.doc(`organizations/${membership.organizationId}`).get();if(organization.exists&&membership.status==="active"&&organization.data()!.status==="active")organizationIds.push(membership.organizationId);}return {uid,status:"active",globalPermissions,organizationIds};}
const audit=(database:FirebaseFirestore.Firestore,event:Record<string,unknown>)=>{const ref=database.collection("auditLogs").doc();return {ref,value:normalizeLegacyAudit(event,{eventId:ref.id,correlationId:ref.id} as never)}};
const id=()=>`contribution-${randomBytes(10).toString("hex")}`;
async function load(database:FirebaseFirestore.Firestore,contributionId:string){const ref=database.doc(`contributions/${contributionId}`),snap=await ref.get();if(!snap.exists)throw Object.assign(new Error("introuvable"),{http:404});return {ref,value:snap.data()!};}
export async function listContributionRecords(uid:string,raw:Record<string,string|undefined>){const actor=await actorContext(uid);rejectInexactFilters(raw);const input=parseContributionQuery(Object.fromEntries(Object.entries(raw).filter(([,v])=>v))) as Record<string,string|number|undefined>&{limit:number},{database}=getLocalFirebaseAdmin();let query:FirebaseFirestore.Query=database.collection("contributions");if(!actor.globalPermissions.includes("editorial.assign")){const author=actor.globalPermissions.includes("draft.self.manage"),reviewer=actor.globalPermissions.some(permission=>["review.assigned.read","review.assigned.comment","editorial.completeness.review","editorial.provenance.verify","editorial.rights.verify","editorial.consent.verify","editorial.ordinary.approve"].includes(permission));if(author&&reviewer)throw Object.assign(new Error("combinaison de périmètres non paginable"),{http:400});query=author?query.where("authorUid","==",uid):query.where("assignedReviewerUids","array-contains",uid);}query=query.orderBy(FieldPath.documentId()).limit(input.limit+1);if(input.cursor)query=query.startAfter(input.cursor);const docs=(await query.get()).docs,page=docs.slice(0,input.limit);return {contributions:page.map(doc=>minimalContribution(doc.data())),nextCursor:docs.length>input.limit?page.at(-1)!.id:null};}
export async function createContributionRecord(uid:string,raw:unknown){const actor=await actorContext(uid);if(!actor.globalPermissions.includes("draft.self.manage"))throw Object.assign(new Error("permission insuffisante"),{http:403});const input=prepareDraftInput(raw),{database}=getLocalFirebaseAdmin(),now=Timestamp.now(),contributionId=id();let organization:FirebaseFirestore.DocumentData|null=null,membership:FirebaseFirestore.DocumentData|null=null;if(input.organizationId){const [o,m]=await Promise.all([database.doc(`organizations/${input.organizationId}`).get(),database.doc(`organizations/${input.organizationId}/memberships/${uid}`).get()]);if(!o.exists||o.data()!.status!=="active"||!m.exists||m.data()!.status!=="active")throw Object.assign(new Error("organisation interdite"),{http:403});organization=o.data()??null;membership=m.data()??null;}const result=createDraft({...input,contributionId,authorUid:uid,authorStatus:"active",organizationStatus:organization?.status,organizationType:organization?.type,verificationStatus:organization?.verificationStatus,mandateStatus:organization?.mandateStatus,membershipStatus:membership?.status,organizationPermissions:[],now}),version=prepareVersion(input.body,"version initiale",1,contributionId,uid,now),event=audit(database,result.auditEvent),batch=database.batch();batch.create(database.doc(`contributions/${contributionId}`),result.contribution);batch.create(database.doc(`contributions/${contributionId}/versions/v1`),version);batch.create(event.ref,event.value);await batch.commit();return minimalContribution(result.contribution);}
export async function getContributionPreviewRecord(uid:string,contributionId:string){const actor=await actorContext(uid),{database}=getLocalFirebaseAdmin(),{value}=await load(database,contributionId),allowed=value.authorUid===uid||value.assignedReviewerUids?.includes(uid)||actor.globalPermissions.includes("editorial.ordinary.publish");if(!allowed)throw Object.assign(new Error("permission insuffisante"),{http:403});const [version,assets]=await Promise.all([database.doc(`contributions/${contributionId}/versions/v${value.currentVersion}`).get(),database.collection(`contributions/${contributionId}/assets`).where("status","==","validated").limit(20).get()]);if(!version.exists)throw Object.assign(new Error("version introuvable"),{http:404});return {contribution:minimalContribution(value),body:version.data()!.body,assets:assets.docs.map(document=>({assetId:document.id,safeFileName:document.data().safeFileName,detectedMimeType:document.data().detectedMimeType}))};}
export async function mutateContributionRecord(uid:string,contributionId:string,input:Record<string,unknown>){const actor=await actorContext(uid),{database}=getLocalFirebaseAdmin(),{ref,value}=await load(database,contributionId);if(value.version!==input.expectedVersion)throw new Error("conflit de version");const now=Timestamp.now();let updated={...value},legacy:Record<string,unknown>,extraRef:FirebaseFirestore.DocumentReference|undefined,extra:FirebaseFirestore.DocumentData|undefined,extraMode:"create"|"set"="create";
if(input.operation==="version"){requireAuthor(actor,value);const number=value.currentVersion+1;extra=prepareVersion(input.body,input.reason,number,contributionId,uid,now);extraRef=database.doc(`contributions/${contributionId}/versions/v${number}`);updated={...value,title:input.title?String(input.title).trim():value.title,summary:input.summary?String(input.summary).trim():value.summary,currentVersion:number,status:"draft",completenessStatus:"incomplete",sourceStatus:"unknown",rightsStatus:"unknown",consentStatus:"not_required",updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"contribution.version_created",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:String(value.currentVersion),nextState:String(number),reason:input.reason,occurredAt:now};}
else if(input.operation==="submit"){requireAuthor(actor,value);updated={...value,status:"submitted",submittedAt:now,updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"contribution.submitted",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:value.status,nextState:"submitted",reason:"soumission interne",occurredAt:now};}
else if(input.operation==="assign"||input.operation==="unassign"){if(!actor.globalPermissions.includes("editorial.assign")||actor.status!=="active")throw Object.assign(new Error("permission insuffisante"),{http:403});const target=String(input.reviewerUid),profile=await database.doc(`users/${target}`).get();if(!profile.exists||profile.data()!.status!=="active"||target===value.authorUid)throw Object.assign(new Error("relecteur invalide"),{http:422});const targetActor=await actorContext(target);if(!targetActor.globalPermissions.some(p=>["review.assigned.read","editorial.completeness.review","editorial.provenance.verify","editorial.rights.verify","editorial.consent.verify","editorial.ordinary.approve"].includes(p))||(value.organizationId&&!targetActor.organizationIds.includes(value.organizationId)))throw Object.assign(new Error("relecteur interdit"),{http:403});const set=new Set<string>(value.assignedReviewerUids);if(input.operation==="assign")set.add(target);else set.delete(target);updated={...value,assignedReviewerUids:[...set],updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"review.assigned",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:null,nextState:input.operation==="assign"?target:null,reason:input.operation==="assign"?"affectation éditoriale":"désaffectation éditoriale",occurredAt:now};}
else if(input.operation==="completeness"){requireAssigned(actor,value,"editorial.completeness.review");const complete=input.value==="complete";updated={...value,completenessStatus:complete?"complete":"incomplete",status:complete?"rights_review":"changes_requested",updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:complete?"contribution.status_changed":"contribution.changes_requested",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:value.status,nextState:updated.status,reason:input.reason,occurredAt:now};}
else if(input.operation==="documentary"){const field=String(input.field),permission=documentaryPermission(field);requireAssigned(actor,value,permission);const allowed=field==="sourceStatus"?["unknown","declared","verified"]:field==="rightsStatus"?["unknown","pending","cleared","not_applicable"]:["not_required","pending","granted","withdrawn"];if(!allowed.includes(String(input.value)))throw new TypeError("statut inconnu");updated={...value,[field]:String(input.value),updatedAt:now,updatedBy:uid,version:value.version+1};const ready=(field==="sourceStatus"?String(input.value):value.sourceStatus)==="verified"&&["cleared","not_applicable"].includes(field==="rightsStatus"?String(input.value):value.rightsStatus)&&["granted","not_required"].includes(field==="consentStatus"?String(input.value):value.consentStatus);if(ready)updated.status="editorial_review";legacy={action:"contribution.updated",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:null,nextState:null,changedFields:[field],reason:`contrôle ${field} version ${value.currentVersion}`,occurredAt:now};}
else if(input.operation==="decision"){requireAssigned(actor,value,"review.assigned.comment");const decision=recordDecision(value,[],{decisionId:database.collection("editorialDecisions").doc().id,reviewerUid:uid,reviewerStatus:"active",permissions:actor.globalPermissions,versionNumber:input.versionNumber,result:input.value,comment:input.reason,roleUsed:"review.assigned.comment",now});extraRef=database.doc(`contributions/${contributionId}/decisions/${decision.decisionId}`);extra=decision;if(input.value==="changes_requested"||input.value==="reject")updated={...value,status:input.value==="reject"?"rejected":"changes_requested",updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"editorial.decision_recorded",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:null,nextState:input.value,reason:input.reason,occurredAt:now};}
else if(input.operation==="approve"){const decisions=(await database.collection(`contributions/${contributionId}/decisions`).where("versionNumber","==",value.currentVersion).get()).docs.map(d=>d.data());const favorable=decisions.find(d=>d.result==="approve");assertOrdinaryApproval(actor,value,favorable??{});updated={...value,status:"approved",updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"contribution.approved",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:value.status,nextState:"approved",reason:input.reason,occurredAt:now};}
else if(input.operation==="editorial_metadata"){if(actor.status!=="active"||!actor.globalPermissions.some(permission=>["draft.self.manage","editorial.ordinary.publish"].includes(permission)))throw Object.assign(new Error("permission insuffisante"),{http:403});if(actor.uid!==value.authorUid&&!actor.globalPermissions.includes("editorial.ordinary.publish"))throw Object.assign(new Error("permission insuffisante"),{http:403});const editorialMetadata=prepareEditorialMetadata(input.metadata);updated={...value,editorialMetadata,updatedAt:now,updatedBy:uid,version:value.version+1};legacy={action:"contribution.updated",actorUid:uid,targetId:contributionId,contributionId,organizationId:value.organizationId,previousState:null,nextState:null,changedFields:["editorialMetadata"],reason:input.reason,occurredAt:now};}
else if(input.operation==="publish"){const versionSnapshot=await database.doc(`contributions/${contributionId}/versions/v${value.currentVersion}`).get();if(!versionSnapshot.exists)throw new TypeError("version introuvable");const publication=preparePublicEventPublication(value,versionSnapshot.data(),input.publication,{actorUid:uid,actorStatus:actor.status,permissions:actor.globalPermissions,now});updated=publication.contribution;legacy=publication.auditEvent;extraRef=database.doc(`publicEvents/${publication.publication.publicationId}`);extra=publication.publication;}
else if(input.operation==="publish_content"){const versionSnapshot=await database.doc(`contributions/${contributionId}/versions/v${value.currentVersion}`).get();if(!versionSnapshot.exists)throw new TypeError("version introuvable");const publicationInput=input.publication as Record<string,unknown>,requestedAssetId=typeof publicationInput?.primaryAssetId==="string"&&publicationInput.primaryAssetId?publicationInput.primaryAssetId:null;let primaryAsset:FirebaseFirestore.DocumentSnapshot|null=null;if(requestedAssetId){const snapshot=await database.doc(`contributions/${contributionId}/assets/${requestedAssetId}`).get();if(!snapshot.exists||snapshot.data()!.status!=="validated"||snapshot.data()!.contributionId!==contributionId)throw new TypeError("média principal invalide");primaryAsset=snapshot;}const primaryAssetId=primaryAsset?.id??null,primaryAssetMimeType=primaryAsset?.data()?.detectedMimeType??null,kind=String(publicationInput?.kind??"");if(["archive","photo"].includes(kind)&&!primaryAssetId)throw new TypeError("un média validé est requis");const publication=preparePublicContentPublication(value,versionSnapshot.data(),publicationInput,{actorUid:uid,actorStatus:actor.status,permissions:actor.globalPermissions,primaryAssetId,primaryAssetMimeType,now});updated=publication.contribution;legacy=publication.auditEvent;extraRef=database.doc(`publicContents/${publication.publication.publicationId}`);extra=publication.publication;}
else if(input.operation==="update_publication"||input.operation==="unpublish"){extraRef=database.doc(`publicEvents/${contributionId}`);const snapshot=await extraRef.get();if(!snapshot.exists)throw new TypeError("publication introuvable");const result=input.operation==="update_publication"?preparePublicEventUpdate(value,snapshot.data(),input.publication,{actorUid:uid,actorStatus:actor.status,permissions:actor.globalPermissions,now}):preparePublicEventUnpublication(value,snapshot.data(),{reason:input.reason},{actorUid:uid,actorStatus:actor.status,permissions:actor.globalPermissions,now});updated=result.contribution;legacy=result.auditEvent;extra=result.publication;extraMode="set";}
else if(input.operation==="unpublish_content"){extraRef=database.doc(`publicContents/${contributionId}`);const snapshot=await extraRef.get();if(!snapshot.exists)throw new TypeError("publication introuvable");const result=preparePublicContentUnpublication(value,snapshot.data(),String(input.reason),{actorUid:uid,actorStatus:actor.status,permissions:actor.globalPermissions,now});updated=result.contribution;legacy=result.auditEvent;extra=result.publication;extraMode="set";}
else throw new TypeError("opération inconnue");
const event=audit(database,legacy);await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");if(extraRef&&extraMode==="set"){const freshPublication=await tx.get(extraRef);if(!freshPublication.exists||freshPublication.data()!.publicationVersion!==extra!.publicationVersion-1)throw new Error("conflit de publication");}tx.set(ref,updated);if(extraRef){if(extraMode==="create")tx.create(extraRef,extra);else tx.set(extraRef,extra);}tx.create(event.ref,event.value);});return minimalContribution(updated);}
