import "server-only";
import { NextRequest, NextResponse } from "next/server";
import { csrfCookiePolicy, validateRequestEnvelope } from "@/lib/crm/session-policy.mjs";
import { resolveCrmSession } from "./session";
export const CRM_HEADERS={"Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"same-origin"};
export async function requireCrmActor(permission:string){const session=await resolveCrmSession();if(session.state!=="authorized")throw Object.assign(new Error(session.state),{http:session.state==="unauthenticated"?401:403});if(!session.permissions.includes(permission))throw Object.assign(new Error("permission insuffisante"),{http:403});return {uid:session.uid,permissions:session.permissions,status:"active" as const};}
export function validateCrmMutation(request:NextRequest){validateRequestEnvelope({method:request.method,contentType:request.headers.get("content-type"),origin:request.headers.get("origin")??"",host:request.headers.get("host")??"",csrfHeader:request.headers.get("x-csrf-token"),csrfCookie:request.cookies.get(csrfCookiePolicy().name)?.value,contentLength:Number(request.headers.get("content-length")??0)});}
export function crmError(error:unknown){const value=error as {http?:number;code?:unknown;message?:string};const code=typeof value.code==="number"?value.code:undefined;const status=value.http??code??(value.message?.includes("conflit")?409:value.message?.includes("invalide")||value.message?.includes("inconnu")?422:500);const message=status===409?"Les données ont changé. Rechargez la fiche.":status===404?"Compte introuvable.":status===401?"Session requise.":status===403?"Action non autorisée.":status===422?"Données invalides.":"Opération impossible.";return NextResponse.json({error:message},{status,headers:CRM_HEADERS});}
export function exactBody(value:unknown,fields:string[]){if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("corps invalide");const keys=Object.keys(value).sort(),expected=[...fields].sort();if(keys.length!==expected.length||keys.some((key,index)=>key!==expected[index]))throw new TypeError("champs inconnus");return value as Record<string,unknown>;}
