import "server-only";
import {randomBytes} from "node:crypto";
import {FieldPath,Timestamp} from "firebase-admin/firestore";
import {getLocalFirebaseAdmin} from "./admin";
import {normalizeLegacyAudit} from "@/lib/crm/audit-log.mjs";
import {createOrganization,effectivePermissions} from "@/lib/crm/organization-authorization.mjs";
import {authorizeGlobal,authorizeScoped,parseMembershipQuery,parseOrganizationQuery,prepareMembershipInvitation,prepareMembershipRoles,prepareMembershipStatus,prepareOrganizationCreation,prepareOrganizationStatus,prepareOrganizationVerification,serializeMembership,serializeOrganization} from "@/lib/crm/organization-management.mjs";
import {membershipQuotaDelta,nextMembershipQuota} from "@/lib/crm/membership-quota.mjs";
import {loadAuthoritativeMemberships,loadMembershipQuotaState} from "./membership-quota-admin";
import {rejectInexactFilters} from "@/lib/crm/request-security.mjs";

type Actor={uid:string;status:"active";globalPermissions:string[];organizationPermissions:Record<string,string[]>};
async function actorContext(uid:string):Promise<Actor>{const {database}=getLocalFirebaseAdmin();const profileSnap=await database.doc(`users/${uid}`).get();if(!profileSnap.exists||profileSnap.data()!.status!=="active")throw Object.assign(new Error("acteur inactif"),{http:403});const profile=profileSnap.data()!;const globalPermissions=effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization:null,membership:null,organizationId:null}).global;const organizationPermissions:Record<string,string[]>={};for(const membership of await loadAuthoritativeMemberships(database,uid)){const organizationSnap=await database.doc(`organizations/${membership.organizationId}`).get();if(organizationSnap.exists)organizationPermissions[membership.organizationId]=effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization:organizationSnap.data(),membership,organizationId:membership.organizationId}).organization;}return {uid,status:"active",globalPermissions,organizationPermissions};}
function audit(database:FirebaseFirestore.Firestore,event:Record<string,unknown>){const ref=database.collection("auditLogs").doc(),correlationId=database.collection("correlations").doc().id;return {ref,value:normalizeLegacyAudit(event,{eventId:ref.id,correlationId} as never)};}
function organizationId(){return `org-${randomBytes(12).toString("hex")}`;}
async function uniqueSlug(database:FirebaseFirestore.Firestore,slug:string,exclude?:string){const matches=await database.collection("organizations").where("slug","==",slug).limit(2).get();if(matches.docs.some(doc=>doc.id!==exclude))throw Object.assign(new Error("slug en doublon"),{http:409});}
export async function organizationActor(uid:string){return actorContext(uid);}
export async function listOrganizations(uid:string,raw:Record<string,string|undefined>){const actor=await actorContext(uid);rejectInexactFilters(raw);const input=parseOrganizationQuery(Object.fromEntries(Object.entries(raw).filter(([,value])=>value)));const {database}=getLocalFirebaseAdmin();let docs:FirebaseFirestore.QueryDocumentSnapshot[]=[];if(actor.globalPermissions.includes("organization.list")){let query:FirebaseFirestore.Query=database.collection("organizations").orderBy(FieldPath.documentId()).limit(input.limit+1);if(input.cursor)query=query.startAfter(input.cursor);docs=(await query.get()).docs;}else{let ids=Object.entries(actor.organizationPermissions).filter(([,permissions])=>permissions.some(permission=>["organization.member.manage","role.local.manage","organization.content.manage","organization.event.manage","committee.communication.prepare"].includes(permission))).map(([id])=>id).sort();if(input.cursor)ids=ids.filter(id=>id>input.cursor);const selected=ids.slice(0,input.limit+1);for(const id of selected){const snap=await database.doc(`organizations/${id}`).get();if(snap.exists)docs.push(snap as FirebaseFirestore.QueryDocumentSnapshot);}}const page=docs.slice(0,input.limit);return {organizations:page.map(doc=>serializeOrganization(doc.data())),nextCursor:docs.length>input.limit?page.at(-1)!.id:null,global:actor.globalPermissions.includes("organization.list")};}
export async function createOrganizationRecord(uid:string,input:unknown){const actor=await actorContext(uid);authorizeGlobal(actor,"organization.create");const clean=prepareOrganizationCreation(input),{database}=getLocalFirebaseAdmin(),now=Timestamp.now();const result=createOrganization({...clean,organizationId:organizationId(),actorUid:uid,now});await uniqueSlug(database,result.organization.slug);const event=audit(database,result.auditEvent);const batch=database.batch();batch.create(database.doc(`organizations/${result.organization.organizationId}`),result.organization);batch.create(event.ref,event.value);await batch.commit();return serializeOrganization(result.organization);}
export async function changeOrganizationRecord(uid:string,id:string,input:{operation:string;value:string;reason:string;expectedVersion:number}){const actor=await actorContext(uid),{database}=getLocalFirebaseAdmin(),ref=database.doc(`organizations/${id}`);const snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{http:404});const current=snapshot.data()!;const now=Timestamp.now();const result=input.operation==="status"?prepareOrganizationStatus(current,input.value,{actor,reason:input.reason,expectedVersion:input.expectedVersion,now}):input.operation==="verification"?prepareOrganizationVerification(current,input.value,{actor,reason:input.reason,expectedVersion:input.expectedVersion,now}):(()=>{throw new TypeError("opération inconnue");})();await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");const event=audit(database,result.auditEvent);tx.set(ref,result.organization);tx.create(event.ref,event.value);});return serializeOrganization(result.organization);}
export async function listMemberships(uid:string,organizationId:string,raw:Record<string,string|undefined>){const actor=await actorContext(uid);authorizeScoped(actor,organizationId,"organization.member.manage");rejectInexactFilters(raw);const input=parseMembershipQuery(Object.fromEntries(Object.entries(raw).filter(([,value])=>value))),{database}=getLocalFirebaseAdmin();let query:FirebaseFirestore.Query=database.collection(`organizations/${organizationId}/memberships`).orderBy(FieldPath.documentId()).limit(input.limit+1);if(input.cursor)query=query.startAfter(input.cursor);const docs=(await query.get()).docs,page=docs.slice(0,input.limit),profiles=new Map<string,FirebaseFirestore.DocumentData>();for(const doc of page){const profile=await database.doc(`users/${doc.id}`).get();if(profile.exists)profiles.set(doc.id,profile.data()!);}return {memberships:page.map(doc=>serializeMembership(doc.data(),profiles.get(doc.id))),nextCursor:docs.length>input.limit?page.at(-1)!.id:null};}
async function syncProjection(database:FirebaseFirestore.Firestore,uid:string){const profile=database.doc(`users/${uid}`),memberships=await loadAuthoritativeMemberships(database,uid);const organizationMemberships=memberships.filter(membership=>membership.status==="active").map(membership=>membership.organizationId).sort();await profile.update({organizationMemberships});}
export async function inviteOrganizationMember(uid:string,organizationId:string,input:unknown){const actor=await actorContext(uid),{database}=getLocalFirebaseAdmin(),now=Timestamp.now();const organization=await database.doc(`organizations/${organizationId}`).get();if(!organization.exists)throw Object.assign(new Error("introuvable"),{http:404});const result=prepareMembershipInvitation(input,{actor,organizationId,now});const profile=await database.doc(`users/${result.membership.uid}`).get();if(!profile.exists||profile.data()!.status==="revoked")throw Object.assign(new Error("compte cible invalide"),{http:422});const ref=database.doc(`organizations/${organizationId}/memberships/${result.membership.uid}`),event=audit(database,result.auditEvent);await database.runTransaction(async tx=>{const existing=await tx.get(ref);if(existing.exists)throw Object.assign(new Error("appartenance existante"),{http:409});const state=await loadMembershipQuotaState(tx,database,result.membership.uid),quota=nextMembershipQuota(state.quota,result.membership.uid,1,now);tx.create(ref,result.membership);tx.set(state.quotaRef,quota);tx.create(event.ref,event.value);});await syncProjection(database,result.membership.uid).catch(()=>{});return serializeMembership(result.membership,profile.data());}
export async function changeMembershipRecord(uid:string,organizationId:string,targetUid:string,input:{operation:string;value:unknown;reason:string;expectedVersion:number}){const actor=await actorContext(uid),{database}=getLocalFirebaseAdmin(),ref=database.doc(`organizations/${organizationId}/memberships/${targetUid}`),snapshot=await ref.get();if(!snapshot.exists)throw Object.assign(new Error("introuvable"),{http:404});const current=snapshot.data()!,now=Timestamp.now();const result=input.operation==="status"?prepareMembershipStatus(current,String(input.value),{actor,reason:input.reason,expectedVersion:input.expectedVersion,now}):input.operation==="roles"?prepareMembershipRoles(current,Array.isArray(input.value)?input.value.map(String):[],{actor,reason:input.reason,expectedVersion:input.expectedVersion,now}):(()=>{throw new TypeError("opération inconnue");})();await database.runTransaction(async tx=>{const fresh=await tx.get(ref);if(!fresh.exists||fresh.data()!.version!==input.expectedVersion)throw new Error("conflit de version");const previous=fresh.data()!,state=await loadMembershipQuotaState(tx,database,targetUid),delta=membershipQuotaDelta(previous.status,result.membership.status),quota=nextMembershipQuota(state.quota,targetUid,delta,now),event=audit(database,result.auditEvent);tx.set(ref,result.membership);if(delta!==0)tx.set(state.quotaRef,quota);tx.create(event.ref,event.value);});await syncProjection(database,targetUid).catch(()=>{});const profile=await database.doc(`users/${targetUid}`).get();return serializeMembership(result.membership,profile.data());}
