import type { Metadata } from "next";
import Link from "next/link";

import SiteFooter from "@/components/layout/SiteFooter";
import SiteHeaderClient from "@/components/layout/SiteHeaderClient";

export const metadata: Metadata = {
  title: "Histoire et mémoire d’Aït Mesbah",
  description:
    "Explorez les premiers repères de l’histoire d’Aït Mesbah, de son organisation ancienne aux migrations du XXe siècle, dans une démarche documentaire progressive.",
  alternates: { canonical: "/histoire-memoire" },
};

type Status = "documented" | "local" | "oral";
const statusLabels: Record<Status, string> = { documented: "Fait documenté", local: "Mémoire locale", oral: "Tradition orale" };
const contents = [["Origines", "origines"], ["Aït Aïssi", "ait-aissi"], ["Conquête", "conquete"], ["1871", "1871"], ["Migrations", "migrations"], ["Grande Guerre", "grande-guerre"], ["Mouvement national", "mouvement-national"], ["Indépendance", "independance"], ["Après 1962", "apres-1962"], ["Nouvelles migrations", "nouvelles-migrations"], ["Archives", "archives"]] as const;

function StatusLabel({ status }: { status: Status }) {
  return <span className={`history-status history-status-${status}`}>{statusLabels[status]}</span>;
}

function TimelineEntry({ id, period, title, status, children }: { id?: string; period: string; title: string; status: Status; children: React.ReactNode }) {
  return <article className="history-entry" id={id}>
    <div className="history-entry-marker" aria-hidden="true" />
    <details className="history-entry-panel">
      <summary>
        <span className="history-entry-period">{period}</span>
        <span className="history-entry-heading"><StatusLabel status={status} /><span className="history-entry-title">{title}</span></span>
        <span className="history-entry-toggle" aria-hidden="true" />
      </summary>
      <div className="history-entry-content">{children}</div>
    </details>
  </article>;
}

export default function HistoryMemoryPage() {
  return <>
    <a className="skip-link" href="#contenu-principal">Aller au contenu principal</a>
    <SiteHeaderClient />
    <main id="contenu-principal" className="history-page" tabIndex={-1}>
      <header className="history-hero">
        <p className="eyebrow light">Un patrimoine à documenter et à transmettre</p>
        <h1>Histoire et mémoire d’Aït Mesbah</h1>
        <p className="history-hero-lead">L’histoire d’Aït Mesbah s’est transmise à travers les récits familiaux, les traditions orales, les gestes artisanaux et les parcours de plusieurs générations. Cette page ouvre un travail documentaire progressif destiné à réunir, vérifier et préserver cette mémoire collective.</p>
        <p className="history-hero-note">Les informations publiées ici distinguent les faits documentés, les traditions orales et les témoignages qui restent à recouper.</p>
      </header>

      <section className="history-method" aria-labelledby="history-method-title"><div><p className="eyebrow">Méthode documentaire</p><h2 id="history-method-title">Lire les niveaux de connaissance</h2></div><dl><div><dt><StatusLabel status="documented" /></dt><dd>Information appuyée par une archive ou un travail historique identifiable.</dd></div><div><dt><StatusLabel status="local" /></dt><dd>Information transmise dans le village et restant à recouper.</dd></div><div><dt><StatusLabel status="oral" /></dt><dd>Récit transmis entre les générations, présenté comme tel.</dd></div></dl></section>

      <nav className="history-toc" aria-label="Sommaire de la page"><span>Parcourir la chronologie</span><ol>{contents.map(([label, id], index) => <li key={id}><a href={`#${id}`}><span aria-hidden="true">{String(index + 1).padStart(2, "0")}</span>{label}</a></li>)}</ol></nav>

      <section className="history-timeline" aria-label="Chronologie historique">
        <div className="history-timeline-intro"><p className="eyebrow">Chronologie ouverte</p><h2>Des origines à la diaspora contemporaine</h2><p>Une histoire en construction, organisée par grandes périodes. Ouvrez chaque repère pour découvrir les faits établis, les mémoires locales et les pistes qui restent à documenter.</p></div>
        <div className="history-timeline-list">
        <TimelineEntry id="origines" period="Origines" title="Des origines probablement anciennes" status="oral"><p>La fondation d’Aït Mesbah pourrait remonter au XVIe siècle. Cette datation demeure une hypothèse de travail : elle devra être confrontée aux traditions orales, aux généalogies familiales et aux sources historiques disponibles.</p><p>Le peuplement du village s’est vraisemblablement constitué progressivement autour de plusieurs groupes familiaux et des différents quartiers composant son territoire.</p><aside className="history-source-note"><strong>Tradition orale</strong><p>Selon une tradition orale rapportée localement, le nom du village serait associé à un premier habitant appelé Yahya ou Mesbah. Cette interprétation n’est pas encore établie par une source historique suffisamment précise.</p></aside></TimelineEntry>

        <TimelineEntry id="ait-aissi" period="Organisation ancienne" title="Aït Mesbah dans la confédération des Aït Aïssi" status="documented"><p>Aït Mesbah appartenait à la tribu des Aït Amar Oufayed, qui comprenait également Taguemount Oukerrouche et Icherdiouène. Cette organisation territoriale et politique s’inscrivait dans la confédération kabyle des Aït Aïssi.</p><p>Les Aït Aïssi occupaient le massif situé entre la vallée du Sébaou et la plaine des Ouadhias, face au Djurdjura.</p><ul className="history-name-list"><li>Aït Zmenzer</li><li>Ihasnaouène</li><li>Iferdiouène</li><li>Aït Douala</li><li>Aït Mahmoud</li><li>Aït Abdelmoumène</li><li>Aït Amar Oufayed</li></ul><p>Comme plusieurs confédérations de Haute Kabylie, les Aït Aïssi conservaient une large autonomie à l’égard de la Régence d’Alger. Leurs relations avec le pouvoir ottoman furent marquées par des périodes de tension et de confrontation.</p><aside className="history-source-note"><strong>À rapprocher des sources</strong><p>Cette organisation historique ne correspond pas aux divisions administratives actuelles. Sa composition, ses limites et la graphie des noms devront être rapprochées de sources historiques et cartographiques.</p></aside></TimelineEntry>

        <TimelineEntry period="1830" title="1830 — Les premiers affrontements" status="local"><p>Après le débarquement des troupes françaises en 1830, des combattants de la confédération des Aït Aïssi auraient répondu à l’appel de Mohamed Zamoum pour participer à la résistance contre l’expédition française, notamment lors des affrontements de Staouéli.</p><p>La participation précise des habitants d’Aït Mesbah reste à documenter à partir des archives militaires et des travaux historiques consacrés à cette période.</p></TimelineEntry>

        <TimelineEntry id="conquete" period="Juin 1857" title="1857 — La conquête de la Kabylie" status="documented"><p>La région fut soumise par l’armée française en juin 1857, pendant la campagne militaire qui entraîna la conquête de la Kabylie.</p><p>Pour Aït Mesbah et les villages voisins, cette rupture ouvrit une période de transformations profondes : installation de l’administration coloniale, modification des structures politiques, pression accrue sur les terres et affaiblissement progressif des formes traditionnelles d’autonomie.</p></TimelineEntry>

        <TimelineEntry id="1871" period="1871" title="1871 — Soulèvement et séquestre" status="documented"><p>En 1871, Aït Mesbah et sa région participèrent au vaste soulèvement qui toucha une grande partie de la Kabylie. Après l’échec de l’insurrection, le village fut frappé par les mesures de séquestre appliquées à de nombreuses communautés kabyles.</p><p>Les conséquences foncières exactes pour les familles du village restent à établir. Les dossiers de séquestre, les archives administratives et les documents fonciers devront permettre de préciser les terres concernées et les effets de ces mesures.</p></TimelineEntry>

        <TimelineEntry id="transformations" period="Fin du XIXe siècle" title="Pauvreté, crises sanitaires et état civil" status="local"><p>À la fin du XIXe siècle, Aït Mesbah fut confronté à une période de grande précarité. La pauvreté et les difficultés alimentaires auraient été aggravées par des crises sanitaires, notamment des épisodes de typhus rapportés dans les années 1890.</p><p>Au cours de cette période, l’administration coloniale développa progressivement l’état civil. Les familles reçurent des patronymes administratifs, introduisant une nouvelle manière d’enregistrer les personnes et les lignées.</p><aside className="history-source-note"><strong>Travail à poursuivre</strong><p>Les dates précises, les conséquences des crises sanitaires et les modalités d’attribution des patronymes devront être étudiées à partir des registres et des archives administratives.</p></aside></TimelineEntry>

        <TimelineEntry id="migrations" period="Fin XIXe — début XXe" title="De la fin du XIXe siècle aux premières migrations" status="documented"><p>La pauvreté, la pression foncière et la recherche de revenus poussèrent de jeunes hommes à quitter temporairement ou durablement le village dès la fin du XIXe siècle et au début du XXe siècle.</p><p>Certains partirent travailler à Tizi Ouzou ou à Alger. D’autres se rendirent dans la plaine de la Mitidja, où ils furent employés dans les exploitations agricoles coloniales.</p><p>Ces mobilités constituèrent les premières étapes d’un mouvement migratoire qui allait progressivement relier Aït Mesbah aux villes algériennes, puis à la France métropolitaine.</p></TimelineEntry>

        <TimelineEntry period="1895–1910" title="L’école de Taguemount Oukerrouche et les premiers diplômés" status="documented"><p>Ouverte en 1895, l’école de garçons de Taguemount Oukerrouche accueillait aussi des enfants d’Aït Mesbah, situé à environ trois kilomètres. L’accès restait très limité : un état administratif de 1945 estimait qu’une cinquantaine de garçons du village seulement pouvaient la fréquenter.</p><p>Le 9 juillet 1910, <em>Le Petit Kabyle</em> publia les résultats du certificat d’études spécial aux écoles d’indigènes. Amar Imache y figure parmi les lauréats de Taguemount Oukerrouche, avec notamment Guernine, Halès, Hemdani et Houili.</p><Link className="history-inline-source" href="/amar-imache#parcours">Voir le document du certificat d’études <span aria-hidden="true">↗</span></Link></TimelineEntry>

        <TimelineEntry period="Début du XXe siècle" title="Les premiers travailleurs en France" status="local"><p>Au début du XXe siècle, l’émigration vers la France métropolitaine prit une place croissante. Des hommes originaires du village partirent travailler dans les mines du nord de la France, dans les Bouches-du-Rhône et surtout dans la région parisienne.</p><p>Cette migration de travail, temporaire ou plus durable selon les parcours, contribua à transformer l’économie des familles et à créer les premiers réseaux reliant Aït Mesbah à la France.</p></TimelineEntry>

        <TimelineEntry id="grande-guerre" period="1914–1918" title="1914–1918 — Les hommes mobilisés" status="local"><p>Pendant la Première Guerre mondiale, plusieurs jeunes hommes d’Aït Mesbah furent mobilisés dans l’armée française, comme de nombreux Algériens soumis à la conscription coloniale.</p><p>La mémoire locale rapporte qu’au moins quatre ou cinq hommes du village auraient péri sur les fronts de Verdun et de la Somme. Cette estimation doit encore être vérifiée à partir des registres matricules, des fiches militaires et des bases consacrées aux soldats morts pendant le conflit.</p></TimelineEntry>

        <TimelineEntry id="mouvement-national" period="Années 1920–1930" title="L’éveil du mouvement national algérien" status="documented"><p>Après la Première Guerre mondiale, l’émigration ouvrière en France devint aussi un espace de rencontres, de débats et d’organisation politique. Dans les milieux immigrés, des travailleurs algériens commencèrent à porter collectivement les revendications d’égalité, de dignité et d’émancipation.</p><p>Fondée à Paris en 1926, l’Étoile nord-africaine joua un rôle majeur dans cette prise de conscience. Les cafés, les foyers, les lieux de travail et les réunions militantes constituèrent autant d’espaces où circulaient les idées et où se formaient de nouveaux engagements.</p><aside className="history-source-note"><strong>Une histoire reliée à l’émigration</strong><p>Cette période permet de comprendre comment les premiers réseaux migratoires reliant la Kabylie à la France participèrent aussi à la naissance du mouvement national.</p></aside></TimelineEntry>

        <TimelineEntry period="Années 1920–1940" title="Amar Imache, du village au militantisme anticolonial" status="documented"><p>Né à Aït Mesbah, Amar Imache s’engagea dans les milieux ouvriers immigrés en France et occupa des responsabilités importantes au sein de l’Étoile nord-africaine, notamment comme secrétaire général.</p><p>Son parcours relie directement l’histoire du village à celle du mouvement national algérien. Son action, ses écrits et sa participation au journal <em>El Ouma</em> témoignent d’une pensée politique attachée à l’émancipation du peuple algérien.</p><p>Une section documentaire spécifique, présentée plus bas, permettra d’approfondir progressivement son itinéraire à partir d’archives et de travaux historiques identifiés.</p></TimelineEntry>

        <TimelineEntry period="5 novembre 1945" title="Aït Mesbah érigé en centre municipal" status="documented"><p>Un état administratif consacré à la création des centres municipaux de Haute Kabylie décrit directement Aït Mesbah comme un village de petits cultivateurs, d’ouvriers agricoles et d’artisans. Il signale une production de poteries usuelles — plats et lampes à huile — ainsi que des objets présentés comme décoratifs.</p><p>Le document recense 1 445 habitants. Il indique aussi que l’école la plus proche se trouve à Taguemount Oukerrouche, à trois kilomètres, qu’un chemin rural carrossable de deux kilomètres relie le village à la route de Tizi Ouzou au marché des Ouadhias et que l’agence postale de Beni Douala est distante de cinq kilomètres.</p><aside className="history-source-note history-found-archive"><strong>Ce que révèle cette archive</strong><p>Cette photographie administrative de 1945 documente simultanément la population, les métiers, la poterie, la scolarisation et l’enclavement relatif du village. Le vocabulaire employé reste celui de l’administration coloniale et doit être lu comme tel.</p><a href="https://alger-roi.fr/Alger/ain_beida/documents_algeriens/synthese_1945_1946/pages/politique/textes/4_creation_centres_municipaux_haute_kabylie.htm" target="_blank" rel="noreferrer">Consulter la transcription du document <span aria-hidden="true">↗</span></a></aside></TimelineEntry>

        <TimelineEntry id="independance" period="1954–1962" title="La guerre d’indépendance et ses blessures" status="local"><p>Comme de nombreux villages de Kabylie, Aït Mesbah fut profondément touché par la guerre d’indépendance. Des habitants participèrent à la lutte, tandis que les familles vécurent les violences, les pertes, les déplacements, la surveillance et les bouleversements de la vie quotidienne.</p><p>La mémoire locale conserve le souvenir de nombreux citoyens du village morts durant cette période. Leur nombre, leurs noms, leurs parcours et les circonstances de leur disparition devront être établis avec les familles, les témoignages, les listes communales et les archives disponibles.</p><aside className="history-source-note"><strong>Un chapitre dédié</strong><p>Un dossier distinct rassemble désormais la chronologie, les vécus, les pistes archivistiques et le projet de mémorial consacré aux années 1954–1962.</p><Link className="history-inline-source" href="/guerre-algerie">Ouvrir le chapitre sur la guerre d’Algérie <span aria-hidden="true">↗</span></Link></aside></TimelineEntry>

        <TimelineEntry id="apres-1962" period="À partir de 1962" title="L’indépendance, l’école et le renouvellement du village" status="local"><p>L’indépendance ouvrit une période de profondes transformations. La croissance démographique, l’accès élargi à l’instruction et la formation de nouvelles générations scolarisées modifièrent progressivement les trajectoires familiales et les aspirations.</p><p>Le village se développa, les habitations se multiplièrent et les modes de vie évoluèrent. L’école devint un levier central de mobilité sociale, permettant à davantage de jeunes de poursuivre des études et d’accéder à de nouveaux métiers.</p><aside className="history-source-note"><strong>À documenter</strong><p>L’évolution de la population, de l’habitat et de la scolarisation pourra être précisée à partir des recensements, des archives scolaires, des photographies et des témoignages.</p></aside></TimelineEntry>

        <TimelineEntry period="1965–1984" title="Le village dans les découpages administratifs de l’Algérie indépendante" status="documented"><p>Le Journal officiel du 7 décembre 1965 rattache explicitement le centre municipal d’Aït Mesbah, avec Taguemount Oukerrouche et Icherdiouène Oufella, à l’organisation territoriale de Beni Douala.</p><p>Le décret du 19 décembre 1984, qui fixe la composition et les limites des communes, cite de nouveau Aït Mesbah parmi les localités constituant la commune de Beni Douala. Ces textes permettent de suivre la continuité administrative du village après l’indépendance.</p><div className="history-source-links"><a href="https://www.joradp.dz/FTP/Jo-Francais/1965/F1965100.pdf" target="_blank" rel="noreferrer">Journal officiel de 1965 ↗</a><a href="https://archive.gazettes.africa/archive/dz/1984/dz-government-gazette-dated-1984-12-19-no-67.pdf" target="_blank" rel="noreferrer">Décret territorial de 1984 ↗</a></div></TimelineEntry>

        <TimelineEntry period="Seconde moitié du XXe siècle" title="Partir en Algérie, partir en France" status="local"><p>Après l’indépendance, les mobilités se poursuivirent et s’intensifièrent. Des habitants quittèrent le village pour s’installer dans les villes algériennes, notamment à Tizi Ouzou, Alger et dans d’autres centres urbains, afin d’étudier, de travailler ou de fonder une famille.</p><p>Dans le même temps, l’émigration vers la France prit une nouvelle ampleur. D’abord souvent liée au travail, elle devint progressivement familiale et durable. Ces départs transformèrent le village sans rompre les liens : retours, entraide, construction de maisons et soutien aux proches continuèrent d’unir les familles établies ailleurs à Aït Mesbah.</p></TimelineEntry>

        <TimelineEntry id="nouvelles-migrations" period="Depuis les années 2000" title="De nouvelles destinations : Canada et États-Unis" status="local"><p>À partir des années 2000, les parcours migratoires se diversifièrent. Aux destinations historiques en Algérie et en France s’ajoutèrent notamment le Canada et les États-Unis.</p><p>Études, opportunités professionnelles et projets familiaux conduisirent une nouvelle génération à s’établir en Amérique du Nord. Les outils numériques, les voyages et les réseaux familiaux permettent aujourd’hui de maintenir des liens réguliers avec le village malgré l’éloignement.</p><aside className="history-source-note"><strong>Une diaspora en mouvement</strong><p>Cartographier ces parcours, recueillir les récits de départ et comprendre la manière dont les nouvelles générations conservent un lien avec Aït Mesbah feront partie du travail documentaire à venir.</p></aside></TimelineEntry>

        <TimelineEntry period="Mémoire quotidienne" title="Des gestes transmis entre les générations" status="local"><p>La mémoire du village ne repose pas uniquement sur les événements politiques et militaires. Elle demeure également dans les métiers, les gestes quotidiens, l’organisation collective et les savoir-faire transmis au sein des familles.</p><ul className="history-practices"><li>Couture de la robe kabyle</li><li>Poterie</li><li>Organisation et entraide villageoises</li></ul><p>L’histoire précise de ces pratiques reste à documenter à partir des objets, des photographies, des témoignages et des archives familiales.</p></TimelineEntry>
        </div>
      </section>

      <section className="history-imache" id="amar-imache"><div><p className="eyebrow light">Une figure du village</p><h2>Amar Imache,<br/>une voix née à Aït Mesbah</h2></div><div className="history-imache-content"><p className="history-imache-lead">Son itinéraire relie intimement l’histoire du village à celle du mouvement national algérien et aux premiers engagements politiques nés dans les milieux immigrés.</p><p>Secrétaire général de l’Étoile nord-africaine et rédacteur en chef d’<em>El Ouma</em>, Amar Imache porta une parole d’émancipation, de souveraineté et d’exigence démocratique. Un chapitre entier réunit désormais les premiers repères de son parcours, ses écrits et les archives qu’il reste à retrouver.</p><Link className="history-imache-link" href="/amar-imache">Découvrir le dossier documentaire <span aria-hidden="true">↗</span></Link></div></section>

      <section className="history-archives" id="archives"><div className="history-archives-heading"><p className="eyebrow">Archives du village</p><h2>Réunir les sources du village</h2></div><ul><li>Photographies anciennes</li><li>Actes et documents administratifs</li><li>Registres d’état civil</li><li>Dossiers fonciers et séquestres</li><li>Lettres et correspondances</li><li>Journaux et coupures de presse</li><li>Cartes et plans</li><li>Objets artisanaux</li><li>Témoignages enregistrés</li><li>Archives associatives et sportives</li><li>Documents relatifs à Amar Imache</li><li>Registres matricules et fiches militaires</li></ul><aside className="history-rights-note"><strong>Publication et droits</strong><p>La présence d’un document dans les archives du projet ne signifie pas automatiquement qu’il peut être publié. Sa provenance, son propriétaire, les personnes représentées, les données personnelles et les droits de diffusion devront être examinés.</p></aside></section>

      <section className="history-conclusion"><p className="eyebrow">Une démarche collective</p><h2>Documenter sans figer</h2><p>Préserver la mémoire d’Aït Mesbah ne consiste pas à imposer une version unique de son histoire. Le projet doit permettre de confronter les sources, d’identifier les incertitudes et de conserver la diversité des récits.</p><p>Les habitants, les familles, les associations, les chercheurs et les membres de la diaspora pourront progressivement participer à ce travail, selon des modalités qui seront annoncées ultérieurement.</p><p className="history-editorial-pledge">Aucun document ou témoignage ne sera publié sans vérification éditoriale et sans examen des autorisations nécessaires.</p><div className="history-actions"><Link className="primary" href="/village">Découvrir le village <span aria-hidden="true">↗</span></Link><Link className="history-secondary-link" href="/contribuer">Comment contribuer</Link></div></section>
    </main>
    <SiteFooter />
  </>;
}
