import { NextRequest,NextResponse } from "next/server";
import { getLocalFirebaseAdmin } from "@/lib/firebase/admin";
import { CRM_PERMISSIONS,csrfCookiePolicy,evaluateCrmAccess,sessionCookiePolicy,validateFreshToken } from "@/lib/crm/session-policy.mjs";
import { loadAuthoritativeMemberships } from "@/lib/firebase/membership-quota-admin";
import { MembershipQuotaError } from "@/lib/crm/membership-quota.mjs";
import { PRIVATE_RESPONSE_HEADERS,validateRequestSecurity } from "@/lib/crm/request-security.mjs";
const secureHeaders=PRIVATE_RESPONSE_HEADERS;
const generic=()=>NextResponse.json({error:"Connexion impossible."},{status:401,headers:secureHeaders});
async function envelope(request:NextRequest){validateRequestSecurity({kind:"session",method:request.method,host:request.headers.get("host"),forwardedHost:request.headers.get("x-forwarded-host"),origin:request.headers.get("origin"),fetchSite:request.headers.get("sec-fetch-site"),fetchMode:request.headers.get("sec-fetch-mode"),fetchDestination:request.headers.get("sec-fetch-dest"),csrfHeader:request.headers.get("x-csrf-token"),csrfCookie:request.cookies.get(csrfCookiePolicy().name)?.value,contentType:request.headers.get("content-type"),contentLength:Number(request.headers.get("content-length")??0),maxBytes:16_384});}
async function accessFor(uid:string){const {auth,database}=getLocalFirebaseAdmin();const identity=await auth.getUser(uid);const snap=await database.doc(`users/${uid}`).get();if(!snap.exists)return {state:"unauthorized"} as const;const profile=snap.data(),memberships=await loadAuthoritativeMemberships(database,uid);const organizations:Array<{membership:FirebaseFirestore.DocumentData;organization:FirebaseFirestore.DocumentData}>=[];for(const membership of memberships){const organization=await database.doc(`organizations/${membership.organizationId}`).get();if(organization.exists)organizations.push({membership,organization:organization.data()!});}return evaluateCrmAccess({authUser:identity,profile,organizations});}
export async function POST(request:NextRequest){try{await envelope(request);const body=await request.json();if(!body||Object.keys(body).length!==1||typeof body.idToken!=="string"||body.idToken.length>8192)return generic();const {projectId,auth}=getLocalFirebaseAdmin();const decoded=await auth.verifyIdToken(body.idToken,true);const uid=validateFreshToken(decoded);const access=await accessFor(uid);if(access.state!=="authorized"||!access.permissions.some((p:string)=>CRM_PERMISSIONS.includes(p)))return generic();const cookie=await auth.createSessionCookie(body.idToken,{expiresIn:12*60*60*1000});const response=NextResponse.json({ok:true},{headers:secureHeaders});response.cookies.set({...sessionCookiePolicy({projectId,emulated:true}),value:cookie});return response;}catch(error){if(error instanceof MembershipQuotaError)return NextResponse.json({error:"Service momentanément indisponible."},{status:500,headers:secureHeaders});return generic();}}
export async function DELETE(request:NextRequest){try{await envelope(request);const {projectId}=getLocalFirebaseAdmin();const response=NextResponse.json({ok:true},{headers:secureHeaders});response.cookies.set({...sessionCookiePolicy({projectId,emulated:true}),value:"",maxAge:0});response.cookies.set({...csrfCookiePolicy(),value:"",maxAge:0});return response;}catch{return NextResponse.json({error:"Déconnexion impossible."},{status:403,headers:secureHeaders});}}
