import type { Metadata } from "next";
import Link from "next/link";
import ArchiveDiscovery from "@/components/archives/ArchiveDiscovery";
import ImageArchiveViewer from "@/components/archives/ImageArchiveViewer";
import PotteryPhotoCollection from "@/components/archives/PotteryPhotoCollection";
import SiteHeaderClient from "@/components/layout/SiteHeaderClient";
import SiteFooter from "@/components/layout/SiteFooter";
import "./reportage.css";

export const metadata: Metadata = {
  title: "Reportage à Aït Mesbah en 1939 — L’artisanat de la poterie",
  description: "Un dossier photographique sur la poterie d’autrefois à Aït Mesbah : gestes du décor, cuisson au sol, objets et vie quotidienne. Seize clichés et une source muséale identifiée.",
  alternates: { canonical: "/histoire-memoire/archives/hiani-debia-1939" },
};

export default function HianiDebiaArchivePage() {
  return <><SiteHeaderClient /><main className="village-archive-page" id="contenu-principal">
    <header className="village-archive-hero"><div><Link href="/histoire-memoire#archives">← Retour aux archives</Link><p className="eyebrow light">Reportage photographique · Archives du village · 1939</p><h1>Reportage à Aït Mesbah<br /><em>en 1939</em></h1></div><div><h2>L’artisanat de la poterie</h2><p>Décorer les pièces, préparer la cuisson, porter les récipients : un regard documentaire sur une activité artisanale et les gestes qui l’inscrivaient dans la vie du village.</p></div></header>
    <section className="village-archive-reading"><div><p className="eyebrow">Le travail de la terre</p><h2>Une production artisanale au cœur du quotidien</h2></div><div><p className="village-archive-lead">Ces photographies donnent à voir les lieux du travail autant que les objets : une cour, des murs de pierre, des outils à portée de main et des poteries réunies près du combustible.</p><p>Il s’agit ici d’une production artisanale, et non d’une industrie mécanisée. Les pièces visibles présentent des formes variées : récipients à anses, coupes sur pied, grands contenants et pièces élancées. Les images permettent de regarder leur décor et leur manipulation, mais pas de mesurer les quantités produites, les revenus ou les circuits de vente.</p><p>Le dossier réunit seize clichés transmis ensemble. L’un d’eux est formellement identifié par la notice PP0193025 : Thérèse Rivière, Aït Mesbah, 1939. Le titre de ce reportage est un intitulé éditorial ; l’attribution de l’ensemble au même lieu, à la même date et au même photographe reste à vérifier cliché par cliché.</p><p><a href="#photographies-1939">Parcourir les 16 photographies ↓</a> · <a href="#source">Voir le document justificatif ↓</a></p></div></section>
    <PotteryPhotoCollection />
    <section className="village-archive-reading"><div><p className="eyebrow">Observer les procédés</p><h2>Du décor à la cuisson</h2></div><div><p className="village-archive-lead">Le décor suit la forme de l’objet : lignes autour du col, bandes sur la panse, points sur les anses et compositions triangulaires.</p><p>Les gros plans montrent le travail manuel sur des récipients déjà façonnés. Les photographies en noir et blanc permettent d’étudier les contrastes et les tracés, mais ne suffisent pas à déterminer les couleurs exactes, la composition des pigments ou le nom des outils.</p><p>Dans les vues de cuisson, les poteries sont regroupées au sol et entourées de matériaux combustibles. D’autres clichés montrent l’empilement de bois, puis une intervention auprès des cendres et de la fumée. Ce rapprochement permet une lecture du procédé, sans établir l’ordre exact des prises de vue ni la durée des opérations.</p><p>La préparation de l’argile, le montage des parois et le séchage ne sont pas clairement visibles dans les fichiers reçus. Ils restent à documenter : cette série ne constitue pas un mode d’emploi complet de fabrication.</p></div></section>
    <section className="village-archive-reading"><div><p className="eyebrow">Lire la photographie</p><h2>Une artisane, des mains, un objet</h2></div><div><p className="village-archive-lead">Le récipient repose sur les genoux de la potière. Ses mains travaillent près de l’anse, au milieu d’un décor de lignes, de points et de triangles.</p><p>Ce cadrage rapproché permet d’observer le geste de décoration. Il ne documente ni la préparation de l’argile ni le façonnage de cette pièce : ces étapes ne doivent pas être déduites de la seule photographie.</p><p>La notice PP0193025, intitulée « Décor », nomme Hiani Debia et situe la scène à Aït Mesbah en 1939. Elle attribue le cliché à Thérèse Rivière.</p><Link href="/artisanat/poterie#photographies-1939">Parcourir le documentaire sur la poterie →</Link></div></section>
    <section className="village-archive-reading"><div><p className="eyebrow">Mémoire familiale</p><h2>Un nom conservé par l’archive</h2></div><div><p className="village-archive-lead">Selon le témoignage de mémoire locale transmis pour ce site, la famille Hiani appartenait au clan Aït El Hadjethe. Le nom de famille Hiani est aujourd’hui éteint au village.</p><p>Cette précision relève de la mémoire familiale et villageoise ; elle ne figure pas dans la notice du musée. L’extinction du patronyme ne signifie pas nécessairement l’absence de descendants.</p></div></section>
    <section className="village-archive-metadata"><p className="eyebrow">Référence du cliché identifié · et non de l’ensemble du reportage</p><dl>
      <div><dt>Personne nommée dans la notice</dt><dd>Hiani Debia</dd></div><div><dt>Photographe</dt><dd>Thérèse Rivière</dd></div><div><dt>Date de prise de vue</dt><dd>1939</dd></div><div><dt>Localisation</dt><dd>Aït Mesbah, Grande Kabylie</dd></div><div><dt>Titre historique</dt><dd>Décor</dd></div><div><dt>Numéro de gestion</dt><dd>PP0193025</dd></div><div><dt>Collection</dt><dd>Musée du quai Branly – Jacques Chirac</dd></div><div><dt>Précédente collection</dt><dd>Musée de l’Homme, Photothèque</dd></div><div><dt>Support catalogué</dt><dd>Tirage argentique sur papier, 9 × 14 cm</dd></div>
    </dl></section>
    <section className="village-archive-reading" id="source"><div><p className="eyebrow">La trace au verso</p><h2>Le document qui étaye l’identification</h2></div><div><p className="village-archive-lead">La capture transmise reproduit les annotations au dos du tirage. On y lit notamment le nom du village, celui de la potière et le tampon du photographe.</p><p>Elle porte les mentions « Décor », « objet 40.8.86 » et le numéro de film « 39-202 ». Ces repères complètent la notice ; ils ne doivent pas être confondus avec son numéro de gestion PP0193025.</p><p>Le champ « numéro de négatif » de la notice indique 1939-214, tandis que le verso porte 39-202. Nous conservons cette différence sans la corriger par supposition. La date de 1939 est renseignée par la notice du musée.</p><p><a href="/archives/poterie-1939/verso-decor-hiani-debia.pdf" target="_blank" rel="noreferrer">Consulter le PDF transmis (1 page) ↗</a></p><p><a href="https://collections.quaibranly.fr/" target="_blank" rel="noreferrer">Consulter le catalogue du musée ↗</a> — rechercher « PP0193025 » ou « Hiani ».</p><aside><strong>Source et reproduction</strong><p>La capture conserve le crédit du musée et l’inscription relative à l’autorisation de reproduction. L’identification d’une source ne constitue pas une autorisation de réutilisation ; les conditions actuelles restent à vérifier auprès du musée.</p></aside></div></section>
    <ImageArchiveViewer src="/archives/poterie-1939/verso-decor-hiani-debia.png" alt="Capture du verso annoté : tampon Thérèse Rivière, Aït Mesbah, Décor, objet 40.8.86, Hiani Debia et film 39-202" title="Pièce justificative · verso annoté du tirage" aspectRatio="1600 / 1154" />
    <ArchiveDiscovery current="reportage" />
  </main><SiteFooter /></>;
}
