import Link from "next/link";
import type {PublicContent} from "@/lib/public-contents-server";
import type {PublicEvent} from "@/data/public-agenda";

const kindLabels={article:"Récit",news:"Actualité",archive:"Archive",photo:"Photographie"} as const;
const eventLabels={collective:"Vie collective",culture:"Culture",sport:"Sport",solidarity:"Solidarité"} as const;
const date=new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"long",year:"numeric"});

export default function HomeEditorialPulse({publications,event,initiatives}:{publications:PublicContent[];event:PublicEvent|null;initiatives:PublicContent[]}){
 const featured=publications[0],secondary=publications.slice(1,3),initiative=initiatives[0];
 return <section className="home-pulse" aria-labelledby="home-pulse-title"><header><div><p className="eyebrow">Le village, aujourd’hui</p><h2 id="home-pulse-title">Ce qui vient d’être<br/><em>transmis et partagé</em></h2></div><p>Archives retrouvées, rendez-vous confirmés et initiatives en cours&nbsp;: cette page évolue désormais au rythme des publications validées par l’équipe éditoriale.</p></header><div className="home-pulse-grid">
  <article className="home-pulse-publications"><div className="home-pulse-title"><span>01</span><div><small>Dernières publications</small><h3>La mémoire s’enrichit</h3></div><Link href="/publications">Tout voir →</Link></div>{featured?<><Link className="home-pulse-featured" href={`/publications/${featured.slug}`}>{featured.primaryAssetId&&featured.primaryAssetMimeType?.startsWith("image/")?<img src={`/api/public/contents/${featured.slug}/media`} alt=""/>:<span aria-hidden="true">ARCHIVES</span>}<div><small>{kindLabels[featured.kind]} · {date.format(new Date(featured.publishedAt))}</small><h4>{featured.title}</h4><p>{featured.summary}</p></div></Link>{secondary.length>0&&<div className="home-pulse-secondary">{secondary.map(item=><Link href={`/publications/${item.slug}`} key={item.publicationId}><small>{kindLabels[item.kind]}</small><strong>{item.title}</strong><span>→</span></Link>)}</div>}</>:<div className="home-pulse-empty"><span>Collection ouverte</span><strong>La première publication se prépare.</strong><p>Les récits et documents validés apparaîtront ici automatiquement.</p><Link href="/contribuer">Partager une archive →</Link></div>}</article>
  <aside className="home-pulse-side"><article className="home-pulse-event"><div className="home-pulse-title"><span>02</span><div><small>Prochain rendez-vous</small><h3>Le village se retrouve</h3></div></div>{event?<><time dateTime={event.startsAt}><strong>{new Date(event.startsAt).getDate().toString().padStart(2,"0")}</strong><span>{new Intl.DateTimeFormat("fr-FR",{month:"long"}).format(new Date(event.startsAt))}</span></time><div><small>{eventLabels[event.category]}</small><h4>{event.title}</h4><p>{event.location} · {event.organizer}</p><Link href={`/agenda/${event.slug}`}>Voir le rendez-vous →</Link></div></>:<div className="home-pulse-empty compact"><strong>Aucune date confirmée</strong><p>Le prochain rendez-vous apparaîtra dès sa validation.</p><Link href="/agenda">Consulter l’agenda →</Link></div>}</article>
  <article className="home-pulse-initiative"><div className="home-pulse-title"><span>03</span><div><small>Initiatives</small><h3>Aït Mesbah en action</h3></div></div>{initiative?<div><small>{date.format(new Date(initiative.publishedAt))}</small><h4>{initiative.title}</h4><p>{initiative.summary}</p><Link href={`/publications/${initiative.slug}`}>Découvrir l’initiative →</Link></div>:<div className="home-pulse-empty compact"><strong>Un espace prêt à vivre</strong><p>Les appels, projets et nouvelles publiés depuis le CRM trouveront ici leur place.</p><Link href="/agir">Agir ensemble →</Link></div>}</article></aside>
 </div></section>;
}
