import assert from "node:assert/strict";

export const ACTIVATION_SCHEMA_VERSION=1;
export const MIN_ACTIVATION_VERSION=1;
export const MAX_ACTIVATION_VERSION=Number.MAX_SAFE_INTEGER-1;
export const ACTIVATION_STATES=Object.freeze(["password_pending","email_verification_pending","mfa_enrollment_pending","ready_for_activation","completed","cancelled","expired"]);
export const ACTIVATION_FIELDS=Object.freeze(["activationId","invitationId","uid","email","approvedGlobalRoles","state","mfaRequired","createdAt","expiresAt","passwordCompletedAt","emailVerifiedAt","mfaCompletedAt","completedAt","cancelledAt","expiredAt","version","schemaVersion"]);
export const ACTIVATION_ROLES=Object.freeze(["technical_owner","contributor","reviewer","editorial_manager"]);
export const MFA_REQUIRED_ROLES=ACTIVATION_ROLES;
const ID=/^[A-Za-z0-9_-]{3,128}$/;

function exactObject(value,fields,label){assert.ok(value&&typeof value==="object"&&!Array.isArray(value),`${label} invalide`);const keys=Object.keys(value).sort(),expected=[...fields].sort();assert.deepEqual(keys,expected,`schéma ${label} invalide`);}
export function validateActivationVersion(value){assert.ok(Number.isSafeInteger(value)&&value>=MIN_ACTIVATION_VERSION&&value<=MAX_ACTIVATION_VERSION,"version d'activation invalide");return value;}
export function nextActivationVersion(value){const current=validateActivationVersion(value);assert.ok(current<MAX_ACTIVATION_VERSION,"version d'activation invalide");return current+1;}
export function validateApprovedGlobalRoles(roles){assert.ok(Array.isArray(roles)&&roles.length===1,"une fonction CRM unique est requise");assert.equal(new Set(roles).size,roles.length,"rôle dupliqué");assert.ok(roles.every(role=>ACTIVATION_ROLES.includes(role)),"rôle inconnu");return Object.freeze([...roles]);}
export function requiresMfa(roles){validateApprovedGlobalRoles(roles);return roles.some(role=>MFA_REQUIRED_ROLES.includes(role));}
function validMillis(value,label){assert.ok(Number.isSafeInteger(value)&&value>=0,`${label} invalide`);return value;}
function nullableMillis(value,label){if(value===null)return null;return validMillis(value,label);}
export function createActivationRecord({activationId,invitationId,uid,email,approvedGlobalRoles,createdAt,expiresAt}){for(const [name,value] of Object.entries({activationId,invitationId,uid}))assert.match(value,ID,`${name} invalide`);assert.match(email,/^[^\s@]+@example\.test$/,"email fictif normalisé requis");assert.equal(email,email.trim().toLowerCase(),"email non normalisé");validMillis(createdAt,"createdAt");validMillis(expiresAt,"expiresAt");assert.ok(expiresAt>createdAt,"expiration invalide");const roles=validateApprovedGlobalRoles(approvedGlobalRoles);return Object.freeze({activationId,invitationId,uid,email,approvedGlobalRoles:roles,state:"password_pending",mfaRequired:requiresMfa(roles),createdAt,expiresAt,passwordCompletedAt:null,emailVerifiedAt:null,mfaCompletedAt:null,completedAt:null,cancelledAt:null,expiredAt:null,version:MIN_ACTIVATION_VERSION,schemaVersion:ACTIVATION_SCHEMA_VERSION});}
export function validateActivationRecord(record){exactObject(record,ACTIVATION_FIELDS,"activation");assert.match(record.activationId,ID);assert.match(record.invitationId,ID);assert.match(record.uid,ID);assert.match(record.email,/^[^\s@]+@example\.test$/);assert.equal(record.email,record.email.trim().toLowerCase());assert.ok(ACTIVATION_STATES.includes(record.state),"état inconnu");assert.deepEqual(record.approvedGlobalRoles,validateApprovedGlobalRoles(record.approvedGlobalRoles));assert.equal(record.mfaRequired,requiresMfa(record.approvedGlobalRoles));validateActivationVersion(record.version);assert.equal(record.schemaVersion,ACTIVATION_SCHEMA_VERSION,"schemaVersion invalide");validMillis(record.createdAt,"createdAt");validMillis(record.expiresAt,"expiresAt");assert.ok(record.expiresAt>record.createdAt,"expiration invalide");for(const field of ["passwordCompletedAt","emailVerifiedAt","mfaCompletedAt","completedAt","cancelledAt","expiredAt"])nullableMillis(record[field],field);const present=field=>record[field]!==null;if(record.state==="password_pending")assert.ok(["passwordCompletedAt","emailVerifiedAt","mfaCompletedAt","completedAt","cancelledAt","expiredAt"].every(field=>!present(field)),"preuves incohérentes");if(record.state==="email_verification_pending")assert.ok(present("passwordCompletedAt")&&!present("emailVerifiedAt")&&!present("mfaCompletedAt")&&!present("completedAt")&&!present("cancelledAt")&&!present("expiredAt"),"preuves incohérentes");if(record.state==="mfa_enrollment_pending")assert.ok(present("passwordCompletedAt")&&present("emailVerifiedAt")&&!present("mfaCompletedAt")&&!present("completedAt")&&!present("cancelledAt")&&!present("expiredAt"),"preuves incohérentes");if(record.state==="ready_for_activation")assert.ok(present("passwordCompletedAt")&&present("emailVerifiedAt")&&(!record.mfaRequired||present("mfaCompletedAt"))&&!present("completedAt")&&!present("cancelledAt")&&!present("expiredAt"),"preuves incohérentes");if(record.state==="completed")assert.ok(present("passwordCompletedAt")&&present("emailVerifiedAt")&&(!record.mfaRequired||present("mfaCompletedAt"))&&present("completedAt")&&!present("cancelledAt")&&!present("expiredAt"),"preuves incohérentes");if(record.state==="cancelled")assert.ok(present("cancelledAt")&&!present("completedAt")&&!present("expiredAt"),"preuves incohérentes");if(record.state==="expired")assert.ok(present("expiredAt")&&record.expiredAt>=record.createdAt&&record.expiredAt>=record.expiresAt&&!present("completedAt")&&!present("cancelledAt"),"preuves incohérentes");return record;}
export function transitionActivation(record,nextState,{now,serverProof=false}={}){validateActivationRecord(record);assert.ok(ACTIVATION_STATES.includes(nextState),"état inconnu");assert.ok(!["completed","cancelled","expired"].includes(record.state),"activation terminale");validMillis(now,"now");const version=nextActivationVersion(record.version);if(now>=record.expiresAt)return Object.freeze({...record,state:"expired",expiredAt:now,version});if(nextState==="cancelled")return Object.freeze({...record,state:nextState,cancelledAt:now,version});assert.notEqual(nextState,"expired","expiration prématurée");assert.equal(serverProof,true,"preuve serveur requise");if(record.state==="password_pending"&&nextState==="email_verification_pending")return Object.freeze({...record,state:nextState,passwordCompletedAt:now,version});if(record.state==="email_verification_pending"&&nextState===(record.mfaRequired?"mfa_enrollment_pending":"ready_for_activation"))return Object.freeze({...record,state:nextState,emailVerifiedAt:now,version});if(record.state==="mfa_enrollment_pending")throw new Error("preuve MFA réelle indisponible localement");if(record.state==="ready_for_activation"&&nextState==="completed"){assert.equal(record.mfaRequired,false,"MFA incomplète");assert.ok(record.passwordCompletedAt!==null&&record.emailVerifiedAt!==null,"preuves incomplètes");return Object.freeze({...record,state:nextState,completedAt:now,version});}throw new Error("transition interdite");}
