import assert from "node:assert/strict";
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { effectivePermissions } from "./organization-authorization.mjs";
import { normalizeEmail } from "./account-lifecycle.mjs";
import { MAX_ACCOUNT_VERSION,nextAccountVersion,validateAccountVersion } from "./account-version.mjs";
import { assertLocalProjectId } from "../config/public-config.mjs";
import { cookiePolicyFor } from "../config/server-config.mjs";

export const SESSION_DURATION_MS=12*60*60*1000;
export const MAX_SESSION_DURATION_MS=SESSION_DURATION_MS;
export const CLOCK_SKEW_MS=5_000;
export const MAX_SAFE_SESSION_VERSION=MAX_ACCOUNT_VERSION;
export const SESSION_SCHEMA_VERSION=1;
export const SESSION_FIELDS=Object.freeze(["sessionId","uid","sessionVersion","status","createdAt","expiresAt","revokedAt","schemaVersion"]);
export const CRM_PERMISSIONS=Object.freeze(["audit.read","asset.self.manage","asset.assigned.read","asset.assigned.review","asset.deletion.manage","draft.self.manage","review.assigned.read","review.assigned.comment","editorial.assign","editorial.completeness.review","editorial.provenance.verify","editorial.rights.verify","editorial.consent.verify","editorial.ordinary.approve","editorial.ordinary.publish","member.approve","member.suspend","profile.assigned.read","organization.create","organization.list","organization.status.manage","organization.verify","organization.member.manage","organization.content.manage","organization.event.manage","committee.communication.prepare","role.local.manage","role.global.manage","settings.manage","security.emergency_remove"]);
export function assertDemoProject(projectId){return assertLocalProjectId(projectId);}
export function sessionCookiePolicy({projectId,emulated}){assertDemoProject(projectId);return cookiePolicyFor(emulated?"local":"production");}
export function csrfCookiePolicy(){return Object.freeze({name:"aitmesbah_csrf_local",httpOnly:true,secure:false,sameSite:"strict",path:"/",maxAge:600});}
export function generateCsrfToken(){return randomBytes(32).toString("base64url");}
export function safeTokenEqual(left,right){if(typeof left!=="string"||typeof right!=="string")return false;const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
export function validateRequestEnvelope({method,contentType,origin,host,csrfHeader,csrfCookie,contentLength=0}){assert.ok(["POST","PATCH","DELETE"].includes(method),"méthode interdite");assert.equal(contentType?.split(";")[0],"application/json","contenu interdit");assert.ok(contentLength<=16_384,"corps excessif");assert.equal(new URL(origin).host,host,"origine interdite");assert.ok(safeTokenEqual(csrfHeader,csrfCookie),"CSRF invalide");return true;}
export function validateFreshToken(decoded,nowSeconds=Math.floor(Date.now()/1000)){assert.equal(typeof decoded?.uid,"string","token invalide");assert.ok(Number.isFinite(decoded.auth_time)&&decoded.auth_time<=nowSeconds&&nowSeconds-decoded.auth_time<300,"authentification trop ancienne");return decoded.uid;}
export function sessionFingerprint(value){assert.equal(typeof value,"string","session invalide");assert.ok(value.length>=32&&value.length<=8192,"session invalide");return createHash("sha256").update(value).digest("hex");}
export function assertSessionVersion(version,{incrementable=false}={}){const value=validateAccountVersion(version);if(incrementable&&value>=MAX_SAFE_SESSION_VERSION)validateAccountVersion(Number.MAX_SAFE_INTEGER);return value;}
export function nextSessionVersion(version){return nextAccountVersion(version);}
export function validateSessionTimes({createdAtMs,expiresAtMs,nowMs}){for(const value of [createdAtMs,expiresAtMs,nowMs])assert.ok(Number.isSafeInteger(value),"horodatage de session invalide");assert.ok(createdAtMs<=nowMs+CLOCK_SKEW_MS,"session future");assert.ok(expiresAtMs>createdAtMs,"dates de session incohérentes");assert.ok(expiresAtMs>nowMs,"session expirée");assert.ok(expiresAtMs-createdAtMs<=MAX_SESSION_DURATION_MS,"durée de session incohérente");return true;}
export function createSessionRecord({cookie,uid,sessionVersion,createdAt,expiresAt}){assert.match(uid,/^[A-Za-z0-9_-]{3,128}$/,"uid invalide");assertSessionVersion(sessionVersion);return Object.freeze({sessionId:sessionFingerprint(cookie),uid,sessionVersion,status:"active",createdAt,expiresAt,revokedAt:null,schemaVersion:SESSION_SCHEMA_VERSION});}
export function validateSessionRecord({cookie,decoded,profile,record,createdAtMs,expiresAtMs,nowMs}){assert.ok(record&&typeof record==="object"&&!Array.isArray(record),"session inconnue");const keys=Object.keys(record).sort(),expected=[...SESSION_FIELDS].sort();assert.deepEqual(keys,expected,"schéma de session invalide");assert.equal(record.schemaVersion,SESSION_SCHEMA_VERSION,"schéma de session invalide");assert.equal(record.sessionId,sessionFingerprint(cookie),"session incohérente");assert.equal(record.uid,decoded?.uid,"session incohérente");assert.equal(record.uid,profile?.uid,"session incohérente");assert.equal(record.status,"active","session révoquée");assert.equal(record.revokedAt,null,"session révoquée");assertSessionVersion(record.sessionVersion);assertSessionVersion(profile?.version);assert.equal(record.sessionVersion,profile.version,"session obsolète");validateSessionTimes({createdAtMs,expiresAtMs,nowMs});return true;}
/** @param {any} input */
export function evaluateCrmAccess({authUser,profile,organizations=[]}){if(!authUser||authUser.disabled)return Object.freeze({state:"unauthenticated"});if(!profile||profile.uid!==authUser.uid||profile.status!=="active")return Object.freeze({state:"unauthorized"});if(authUser.emailVerified!==true||typeof authUser.email!=="string"||normalizeEmail(authUser.email)!==profile.email)return Object.freeze({state:"unauthorized"});const permissions=new Set(effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization:null,membership:null,organizationId:null}).global);for(const {organization,membership} of organizations){const result=effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization,membership,organizationId:organization.organizationId});result.organization.forEach(p=>permissions.add(p));}const crm=[...permissions].filter(p=>CRM_PERMISSIONS.includes(p)).sort();if(!crm.length)return Object.freeze({state:"unauthorized"});return Object.freeze({state:"authorized",uid:profile.uid,displayName:profile.displayName,permissions:Object.freeze(crm),sessionVersion:profile.version});}
export function clearCookiePolicy(policy){return Object.freeze({...policy,maxAge:0,value:""});}
