import assert from "node:assert/strict";
import { randomBytes, timingSafeEqual } from "node:crypto";
import { effectivePermissions } from "./organization-authorization.mjs";

export const SESSION_DURATION_MS=12*60*60*1000;
export const CRM_PERMISSIONS=Object.freeze(["asset.self.manage","asset.assigned.read","asset.assigned.review","asset.deletion.manage","draft.self.manage","review.assigned.read","review.assigned.comment","editorial.assign","editorial.completeness.review","editorial.provenance.verify","editorial.rights.verify","editorial.consent.verify","editorial.ordinary.approve","editorial.ordinary.publish","member.approve","member.suspend","profile.assigned.read","organization.create","organization.list","organization.status.manage","organization.verify","organization.member.manage","organization.content.manage","organization.event.manage","committee.communication.prepare","role.local.manage","role.global.manage","settings.manage","security.emergency_remove"]);
export function assertDemoProject(projectId){assert.match(projectId??"",/^demo-/,"projet local requis");assert.notEqual(projectId,"aitmesbah-d945d");assert.notEqual(projectId,"ccs-compta");return projectId;}
export function sessionCookiePolicy({projectId,emulated}){assertDemoProject(projectId);if(emulated)return Object.freeze({name:"aitmesbah_session_local",httpOnly:true,secure:false,sameSite:"strict",path:"/",maxAge:SESSION_DURATION_MS/1000});return Object.freeze({name:"__Host-aitmesbah_session",httpOnly:true,secure:true,sameSite:"strict",path:"/",maxAge:SESSION_DURATION_MS/1000});}
export function csrfCookiePolicy(){return Object.freeze({name:"aitmesbah_csrf_local",httpOnly:true,secure:false,sameSite:"strict",path:"/",maxAge:600});}
export function generateCsrfToken(){return randomBytes(32).toString("base64url");}
export function safeTokenEqual(left,right){if(typeof left!=="string"||typeof right!=="string")return false;const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
export function validateRequestEnvelope({method,contentType,origin,host,csrfHeader,csrfCookie,contentLength=0}){assert.ok(["POST","PATCH","DELETE"].includes(method),"méthode interdite");assert.equal(contentType?.split(";")[0],"application/json","contenu interdit");assert.ok(contentLength<=16_384,"corps excessif");assert.equal(new URL(origin).host,host,"origine interdite");assert.ok(safeTokenEqual(csrfHeader,csrfCookie),"CSRF invalide");return true;}
export function validateFreshToken(decoded,nowSeconds=Math.floor(Date.now()/1000)){assert.equal(typeof decoded?.uid,"string","token invalide");assert.ok(Number.isFinite(decoded.auth_time)&&decoded.auth_time<=nowSeconds&&nowSeconds-decoded.auth_time<300,"authentification trop ancienne");return decoded.uid;}
/** @param {any} input */
export function evaluateCrmAccess({authUser,profile,organizations=[]}){if(!authUser||authUser.disabled)return Object.freeze({state:"unauthenticated"});if(!profile||profile.uid!==authUser.uid||profile.status!=="active")return Object.freeze({state:"unauthorized"});const permissions=new Set(effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization:null,membership:null,organizationId:null}).global);for(const {organization,membership} of organizations){const result=effectivePermissions({accountStatus:profile.status,globalRoles:profile.globalRoles,organization,membership,organizationId:organization.organizationId});result.organization.forEach(p=>permissions.add(p));}const crm=[...permissions].filter(p=>CRM_PERMISSIONS.includes(p)).sort();if(!crm.length)return Object.freeze({state:"unauthorized"});return Object.freeze({state:"authorized",uid:profile.uid,displayName:profile.displayName,permissions:Object.freeze(crm)});}
export function clearCookiePolicy(policy){return Object.freeze({...policy,maxAge:0,value:""});}
