"use client";
import {FormEvent,useState} from "react";
type Account={uid:string;displayName:string;email?:string;status:string;globalRoles:string[];version:number;authDisabled?:boolean};
const roles=["pending_member","approved_member","contributor","reviewer","editorial_manager","memory_archives_referent","community_manager"];
const labels:Record<string,string>={pending_member:"Membre en attente",approved_member:"Membre approuvé",contributor:"Contributeur",reviewer:"Relecteur",editorial_manager:"Responsable éditorial",memory_archives_referent:"Référent mémoire et archives",community_manager:"Responsable communautaire"};
async function mutate(url:string,method:string,body:unknown){const csrf=await fetch("/api/auth/csrf",{cache:"no-store"});const {csrfToken}=await csrf.json();const response=await fetch(url,{method,headers:{"Content-Type":"application/json","X-CSRF-Token":csrfToken},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error??"Opération impossible.");return value;}
export function AccountManager({initial,nextCursor,permissions,currentUid}:{initial:Account[];nextCursor:string|null;permissions:readonly string[];currentUid:string}){const [accounts,setAccounts]=useState(initial),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const canInvite=permissions.includes("member.approve"),canStatus=permissions.includes("member.suspend")||canInvite,canRoles=permissions.includes("role.global.manage");
async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const form=new FormData(event.currentTarget);try{const account=await mutate("/api/crm/accounts","POST",{displayName:form.get("displayName"),email:form.get("email")});setAccounts(current=>[account,...current]);event.currentTarget.reset();setNotice("Invitation préparée sans envoi d’email.");}catch(error){setNotice(error instanceof Error?error.message:"Opération impossible.");}finally{setBusy(false);}}
async function change(account:Account,event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const form=new FormData(event.currentTarget),operation=String(form.get("operation"));const value=operation==="roles"?roles.filter(role=>form.getAll("roles").includes(role)):form.get("status");try{const updated=await mutate(`/api/crm/accounts/${account.uid}`,"PATCH",{operation,value,reason:form.get("reason"),expectedVersion:account.version});setAccounts(current=>current.map(item=>item.uid===account.uid?updated:item));setNotice("Compte mis à jour et décision auditée.");}catch(error){setNotice(error instanceof Error?error.message:"Opération impossible.");}finally{setBusy(false);}}
return <div className="crm-accounts-manager">{notice&&<p className="crm-notice" role="status" tabIndex={-1}>{notice}</p>}{canInvite&&<section className="crm-panel" aria-labelledby="invite-heading"><h2 id="invite-heading">Préparer une invitation</h2><p>Aucun email ni mot de passe n’est envoyé.</p><form className="crm-account-form" onSubmit={invite}><label>Nom d’usage<input name="displayName" required maxLength={80}/></label><label>Adresse électronique<input name="email" type="email" required autoComplete="off"/></label><button disabled={busy}>Préparer l’invitation</button></form></section>}<section className="crm-panel" aria-labelledby="accounts-heading"><h2 id="accounts-heading">Comptes</h2><form className="crm-filters" method="get"><label>Statut<select name="status" defaultValue=""><option value="">Tous</option>{["invited","active","suspended","revoked"].map(value=><option key={value}>{value}</option>)}</select></label><label>Préfixe du nom<input name="prefix" minLength={2} maxLength={40}/></label><button>Filtrer</button></form><ul className="crm-account-list">{accounts.map(account=><li key={account.uid}><header><div><strong>{account.displayName}</strong>{account.email&&<small>{account.email}</small>}</div><span>{account.status} · Auth {account.authDisabled?"désactivée":"active"}</span></header><p>{account.globalRoles.length?account.globalRoles.map(role=>labels[role]??role).join(" · "):"Aucun rôle global"}</p>{account.uid===currentUid?<p className="crm-self-note">Votre propre compte ne peut pas être modifié ici.</p>:(canStatus||canRoles)&&!account.globalRoles.includes("technical_owner")&&<form className="crm-account-action" onSubmit={event=>change(account,event)}><label>Opération<select name="operation" defaultValue={canStatus?"status":"roles"}><option value="status" disabled={!canStatus}>Changer le statut</option><option value="roles" disabled={!canRoles}>Modifier les rôles</option></select></label><label>Nouveau statut<select name="status" defaultValue={account.status}>{["invited","active","suspended","revoked"].map(value=><option key={value}>{value}</option>)}</select></label><fieldset disabled={!canRoles}><legend>Rôles ordinaires</legend>{roles.map(role=><label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={account.globalRoles.includes(role)}/>{labels[role]}</label>)}</fieldset><label>Motif<textarea name="reason" required maxLength={500}/></label><button disabled={busy}>Confirmer l’opération</button></form>}</li>)}</ul>{nextCursor&&<a className="crm-next" href={`?cursor=${encodeURIComponent(nextCursor)}`}>Page suivante</a>}</section></div>}
