"use client";

import {FormEvent,useState} from "react";

type Contribution={contributionId:string;title:string};
type Asset={assetId:string;contributionId:string;safeFileName:string;declaredMimeType:string;detectedMimeType:string|null;size:number|null;sha256:string|null;status:string;scanStatus:string;sourceStatus:string;rightsStatus:string;consentStatus:string;deletionRequestedBy:string|null;deletionExecutionStatus:string|null;version:number};
const ANTIVIRUS_WARNING="Analyse antivirus indisponible — ce fichier n’est pas déclaré exempt de logiciel malveillant.";

async function csrf(){const response=await fetch("/api/auth/csrf",{cache:"no-store"});return (await response.json()).csrfToken;}
async function json(url:string,method="GET",body?:unknown){const headers:Record<string,string>={};if(body){headers["Content-Type"]="application/json";headers["X-CSRF-Token"]=await csrf();}const response=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined,cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error??"Opération impossible.");return value;}

export function AssetManager({contributions,permissions,initialDeletionRequests=[]}:{contributions:Contribution[];permissions:readonly string[];initialDeletionRequests?:Asset[]}){
  const [selected,setSelected]=useState<Contribution|null>(null),[assets,setAssets]=useState<Asset[]>([]),[deletionRequests,setDeletionRequests]=useState<Asset[]>(initialDeletionRequests),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const canDelete=permissions.includes("asset.deletion.manage");
  async function open(contribution:Contribution){setSelected(contribution);try{setAssets((await json(`/api/crm/contributions/${contribution.contributionId}/assets`)).assets);setNotice("");}catch(error){setNotice(error instanceof Error?error.message:"Erreur");}}
  async function refreshDeletionRequests(){if(!canDelete)return;try{setDeletionRequests((await json("/api/crm/assets/deletion-requests?limit=25")).requests);}catch(error){setNotice(error instanceof Error?error.message:"Erreur");}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget,file=new FormData(form).get("file");if(!(file instanceof File))return;setBusy(true);try{const body=new FormData();body.set("file",file);const response=await fetch(`/api/crm/contributions/${selected.contributionId}/assets`,{method:"POST",headers:{"X-CSRF-Token":await csrf()},body}),value=await response.json();if(!response.ok)throw new Error(value.error);setAssets(current=>[value,...current]);form.reset();setNotice(ANTIVIRUS_WARNING);}catch(error){setNotice(error instanceof Error?error.message:"Erreur");}finally{setBusy(false);}}
  async function mutate(asset:Asset,event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);try{const value=await json(`/api/crm/contributions/${asset.contributionId}/assets/${asset.assetId}`,"PATCH",{operation:data.get("operation"),field:data.get("field"),value:data.get("value"),reason:data.get("reason"),expectedVersion:asset.version});setAssets(current=>current.map(item=>item.assetId===value.assetId?value:item));setDeletionRequests(current=>current.filter(item=>item.assetId!==value.assetId));setNotice("Décision privée enregistrée et auditée.");await refreshDeletionRequests();}catch(error){setNotice(error instanceof Error?error.message:"Erreur");}finally{setBusy(false);}}
  return <div className="crm-assets-manager">
    {notice&&<p role="status" className="crm-notice">{notice}</p>}
    {canDelete&&<section className="crm-panel" aria-labelledby="deletion-title"><h2 id="deletion-title">Demandes de suppression</h2><p>File administrative privée, limitée aux 25 premières demandes.</p>{deletionRequests.length===0?<p>Aucune demande en attente.</p>:<ul className="crm-account-list">{deletionRequests.map(asset=><li key={`${asset.contributionId}-${asset.assetId}`}><strong>{asset.safeFileName}</strong><p>Contribution {asset.contributionId} · état {asset.status}</p><form className="crm-account-action" onSubmit={event=>mutate(asset,event)}><input type="hidden" name="operation" value="delete"/><label>Motif d’exécution<textarea name="reason" required maxLength={500}/></label><button disabled={busy}>Supprimer définitivement les octets</button></form></li>)}</ul>}</section>}
    <section className="crm-panel"><h2>Contributions autorisées</h2>{contributions.length===0?<p>Aucune contribution accessible.</p>:<ul className="crm-account-list">{contributions.map(contribution=><li key={contribution.contributionId}><strong>{contribution.title}</strong><button type="button" onClick={()=>open(contribution)}>Gérer les fichiers privés</button></li>)}</ul>}</section>
    {selected&&<section className="crm-panel"><h2>Fichiers de {selected.title}</h2>{permissions.includes("asset.self.manage")&&<form className="crm-account-form" onSubmit={upload}><label>JPEG, PNG, WebP ou PDF<input name="file" type="file" required accept=".jpg,.jpeg,.png,.webp,.pdf"/></label><button disabled={busy}>Téléverser en quarantaine</button></form>}<ul className="crm-account-list">{assets.map(asset=><li key={asset.assetId}><strong>{asset.safeFileName}</strong><p>{asset.declaredMimeType} · {asset.size??0} octets · {asset.status} · analyse {asset.scanStatus}</p><p>{ANTIVIRUS_WARNING}</p><p>SHA-256 : {asset.sha256} · provenance {asset.sourceStatus} · droits {asset.rightsStatus} · consentement {asset.consentStatus}</p>{["quarantined","validated"].includes(asset.status)&&<a className="crm-button" href={`/api/crm/contributions/${asset.contributionId}/assets/${asset.assetId}/download`}>Télécharger le fichier privé</a>}<form className="crm-account-action" onSubmit={event=>mutate(asset,event)}><label>Opération<select name="operation"><option value="validate" disabled={!permissions.includes("asset.assigned.review")}>Valider humainement</option><option value="reject" disabled={!permissions.includes("asset.assigned.review")}>Rejeter</option><option value="withdraw" disabled={!permissions.includes("asset.self.manage")}>Retirer</option><option value="clearance" disabled={!permissions.some(permission=>permission.endsWith(".verify"))}>Contrôle documentaire</option><option value="request_deletion" disabled={!permissions.includes("asset.self.manage")}>Demander la suppression</option></select></label><label>Domaine<select name="field"><option value="rightsStatus">Droits</option><option value="consentStatus">Consentement</option><option value="sourceStatus">Provenance</option></select></label><label>Valeur<input name="value" maxLength={32}/></label><label>Motif<textarea name="reason" required maxLength={500}/></label><button disabled={busy}>Confirmer</button></form></li>)}</ul></section>}
  </div>;
}
