"use client";
import { Fragment, useEffect, useState } from "react";
import Brand from "@/components/layout/Brand";
import HeroSection from "@/components/home/HeroSection";
import QuickLinks from "@/components/home/QuickLinks";
import VillageIntro from "@/components/home/VillageIntro";
import { footerCommunityLinks, footerDiscoverLinks, mainNavigation } from "@/data/navigation";
import { contributionTypes, events, memoryItems, news, places, voiceCategories } from "@/data/home";
export default function Home(){const[menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[search,setSearch]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>40);f();addEventListener("scroll",f);return()=>removeEventListener("scroll",f)},[]);return <main>
<header className={`site-header ${scrolled||menu?"solid":""}`}><Brand/><nav className={menu?"open":""} onClick={()=>setMenu(false)}>{mainNavigation.map(item=><a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="header-actions"><button className="lang">FR⌄</button><button className="icon-btn" onClick={()=>setSearch(!search)} aria-label="Rechercher">⌕</button><a className="contribute small" href="#contribuer">Contribuer ↗</a><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?"×":"☰"}</button></div>{search&&<div className="searchbar"><label>Que cherchez-vous ?</label><input autoFocus placeholder="Une archive, un événement, un lieu…"/><button onClick={()=>setSearch(false)}>Fermer</button></div>}</header>
<HeroSection />
<QuickLinks />
<div className="word-river" aria-hidden="true"><div>TERRE <i>✦</i> TRANSMISSION <i>✦</i> VILLAGE <i>✦</i> MÉMOIRE <i>✦</i> SOLIDARITÉ <i>✦</i> AVENIR <i>✦</i></div></div>
<VillageIntro />
<section id="memoire" className="memory dark-section section-pad"><div className="section-head"><div><p className="eyebrow light">Histoire & transmission</p><h2>Une histoire<br/>à <em>transmettre</em></h2></div><p>Les souvenirs racontés par nos aînés, les photographies de famille et les récits de chacun composent une histoire précieuse. Ensemble, préservons-la.</p></div><div className="memory-grid"><article className="feature-card"><div className="feature-image photo-placeholder"><span>Archive photographique<br/><small>à intégrer</small></span></div><div><span className="card-no">01</span><h3>Aux origines<br/>du village</h3><p>Un récit documenté des origines et de l’évolution d’Aït Mesbah — contenu historique à compléter et à valider collectivement.</p><a href="#contribuer">Découvrir le récit →</a></div></article><div className="memory-list">{memoryItems.map(item=><article key={item.number}><span>{item.number}</span><div><small>{item.category}</small><h3>{item.title}</h3><p>{item.description}</p></div><b>↗</b></article>)}</div></div></section>
<section className="places section-pad"><div className="section-head light-head"><div><p className="eyebrow">Chemins & patrimoine</p><h2>Les lieux qui racontent<br/><em>Aït Mesbah</em></h2></div><p>Fontaines, places, chemins et points de vue : chaque lieu porte une mémoire. Les noms et contenus seront ajoutés avec les habitants.</p></div><div className="place-grid">{places.map(place=><article className={`place${place.large?" large":""} photo-placeholder`} key={place.title}><span className="draft">{place.draftLabel}</span><div><small>{place.category}</small><h3>{place.title}</h3>{place.description&&<p>{place.description}</p>}</div></article>)}</div><a className="outline-btn" href="#">Explorer tous les lieux →</a></section>
<section id="vivre" className="news section-pad"><div className="section-head light-head"><div><p className="eyebrow">Aujourd’hui à Aït Mesbah</p><h2>La vie du <em>village</em></h2></div><a className="text-link" href="#">Toutes les actualités →</a></div><div className="news-grid">{news.map((n,i)=><article className="news-card" key={n.title}><div className={`news-image ${n.tone}`}><span>Photographie à intégrer</span><b>0{i+1}</b></div><div><p className="meta"><span>{n.tag}</span> · DATE À COMPLÉTER</p><h3>{n.title}</h3><p>{n.text}</p><a href="#">Lire la suite →</a></div></article>)}</div></section>
<section id="agenda" className="agenda section-pad"><div><p className="eyebrow light">À vos agendas</p><h2>Les prochains<br/><em>rendez-vous</em></h2><p className="agenda-intro">Fêtes, rencontres sportives, actions associatives et temps forts de la diaspora.</p><a className="primary pale" href="#">Voir tout l’agenda →</a></div><div className="event-list">{events.map(e=><article key={e.title}><div className="date"><b>—</b><span>DATE</span></div><div><small>{e.kind}</small><h3>{e.title}</h3><p>{e.meta}</p></div><span className="event-arrow">↗</span></article>)}</div></section>
<section className="voices section-pad"><p className="eyebrow">Paroles d’Aït Mesbah</p><blockquote>« Notre village vit dans les souvenirs de ceux qui sont partis, dans les gestes de ceux qui y restent, et dans les rêves de ceux qui reviendront. »</blockquote><p className="quote-note">Texte éditorial provisoire — à remplacer par un témoignage authentique</p><div className="voice-types">{voiceCategories.map((category,index)=><Fragment key={category}><span>{category}</span>{index<voiceCategories.length-1&&<i/>}</Fragment>)}</div></section>
<section id="diaspora" className="diaspora section-pad"><div className="world">⌁<span>PARIS</span><span>MONTRÉAL</span><span>ALGER</span><span>AILLEURS</span></div><div className="diaspora-copy"><p className="eyebrow light">La communauté sans frontières</p><h2>Aït Mesbah<br/><em>au-delà des montagnes</em></h2><p>De l’Algérie à la France, du Canada à d’autres horizons, la diaspora continue de faire vivre les liens, les souvenirs et les projets du village.</p><div className="diaspora-actions"><a href="#contribuer">Raconter mon parcours →</a><a href="#contribuer">Envoyer une archive →</a></div></div></section>
<section id="contribuer" className="contribution section-pad"><div><p className="eyebrow">Notre mémoire vous appartient</p><h2>Vous avez une photo,<br/>un document, <em>une histoire ?</em></h2><p>Contribuez à enrichir la mémoire collective d’Aït Mesbah. Chaque témoignage sera étudié et valorisé avec soin.</p></div><form onSubmit={e=>e.preventDefault()}><label>Je souhaite partager<select defaultValue=""><option value="" disabled>Choisir une contribution</option>{contributionTypes.map(type=><option key={type.label}>{type.label}</option>)}</select></label><label>Mon adresse e-mail<input type="email" placeholder="votre@email.com"/></label><button className="primary">Commencer ma contribution →</button><small>Formulaire de démonstration — aucune donnée n’est envoyée.</small></form></section>
<footer><div className="footer-main"><div><Brand/><p>La mémoire d’un village, partagée entre les générations et au-delà des frontières.</p></div><div><h4>Découvrir</h4>{footerDiscoverLinks.map(item=><a href={item.href} key={item.label}>{item.label}</a>)}</div><div><h4>Communauté</h4>{footerCommunityLinks.map(item=><a href={item.href} key={item.label}>{item.label}</a>)}</div><div><h4>Rester en lien</h4><p>Recevez les nouvelles du village.</p><form className="newsletter"><input type="email" placeholder="Votre adresse e-mail"/><button>→</button></form></div></div><div className="footer-bottom"><span>© 2026 Aït Mesbah — Projet communautaire</span><span>Mentions légales · Confidentialité · Crédits</span><span>FR · KAB · ع</span></div></footer></main>}
