import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { ACTIVATION_FIELDS,ACTIVATION_ROLES,ACTIVATION_STATES,MAX_ACTIVATION_VERSION,MIN_ACTIVATION_VERSION,createActivationRecord,nextActivationVersion,requiresMfa,transitionActivation,validateActivationRecord,validateActivationVersion,validateApprovedGlobalRoles } from "../../lib/crm/activation-policy.mjs";

const fixture=(role="contributor")=>createActivationRecord({activationId:"activation_test",invitationId:"invitation_test",uid:"user_test",email:"user@example.test",approvedGlobalRoles:[role],createdAt:1000,expiresAt:5000});
test("catalogues et schéma canonique ont exactement dix-sept champs",()=>{assert.equal(ACTIVATION_FIELDS.length,17);assert.deepEqual(ACTIVATION_FIELDS,["activationId","invitationId","uid","email","approvedGlobalRoles","state","mfaRequired","createdAt","expiresAt","passwordCompletedAt","emailVerifiedAt","mfaCompletedAt","completedAt","cancelledAt","expiredAt","version","schemaVersion"]);assert.deepEqual(ACTIVATION_STATES,["password_pending","email_verification_pending","mfa_enrollment_pending","ready_for_activation","completed","cancelled","expired"]);assert.deepEqual(ACTIVATION_ROLES,["technical_owner","contributor","reviewer","editorial_manager"]);assert.deepEqual(Object.keys(fixture()).sort(),[...ACTIVATION_FIELDS].sort());assert.equal(fixture().expiredAt,null);});
test("schéma pur refuse champ supplémentaire, champ absent et toute pseudo-date",()=>{const value=fixture();assert.throws(()=>validateActivationRecord({...value,unknown:true}),/schéma/);const missing={...value};delete missing.expiredAt;assert.throws(()=>validateActivationRecord(missing),/schéma/);for(const invalid of [new Date(),{toMillis:()=>1000},"1000",NaN,Infinity])assert.throws(()=>validateActivationRecord({...value,createdAt:invalid}));});
test("états terminaux imposent des preuves temporelles exclusives",()=>{const value=fixture();assert.throws(()=>validateActivationRecord({...value,state:"expired"}),/preuves/);assert.throws(()=>validateActivationRecord({...value,expiredAt:5000}),/preuves/);assert.throws(()=>validateActivationRecord({...value,state:"cancelled",cancelledAt:2000,expiredAt:5000}),/preuves/);assert.throws(()=>validateActivationRecord({...value,state:"completed",passwordCompletedAt:1500,emailVerifiedAt:1600,mfaCompletedAt:1700,completedAt:1800,expiredAt:5000}),/preuves/);assert.throws(()=>validateActivationRecord({...value,state:"expired",expiredAt:4999}),/preuves/);assert.equal(validateActivationRecord({...value,state:"expired",expiredAt:5000}).expiredAt,5000);});
test("une fonction CRM unique, connue et sans doublon est imposée",()=>{for(const role of ACTIVATION_ROLES)assert.deepEqual(validateApprovedGlobalRoles([role]),[role]);for(const roles of [[],["administrator"],["unknown"],["reviewer","reviewer"],["contributor","reviewer"]])assert.throws(()=>validateApprovedGlobalRoles(roles));});
test("MFA est obligatoire pour les quatre fonctions",()=>{for(const role of ACTIVATION_ROLES)assert.equal(requiresMfa([role]),true);});
test("versions sont bornées et l'incrément exact ne sort jamais du domaine",()=>{assert.equal(MIN_ACTIVATION_VERSION,1);assert.equal(validateActivationVersion(1),1);assert.equal(validateActivationVersion(MAX_ACTIVATION_VERSION),MAX_ACTIVATION_VERSION);assert.equal(nextActivationVersion(MAX_ACTIVATION_VERSION-1),MAX_ACTIVATION_VERSION);for(const invalid of [MAX_ACTIVATION_VERSION,Number.MAX_SAFE_INTEGER,0,-1,1.5,"1",NaN,Infinity])assert.throws(()=>invalid===MAX_ACTIVATION_VERSION?nextActivationVersion(invalid):validateActivationVersion(invalid));});
test("transition utilise l'incrément central et ne mute pas après refus de borne",async()=>{const source=await readFile("lib/crm/activation-policy.mjs","utf8");assert.doesNotMatch(source,/version\s*\+\s*1/);assert.match(source,/nextActivationVersion\(record\.version\)/);const value={...fixture(),version:MAX_ACTIVATION_VERSION};assert.throws(()=>transitionActivation(value,"cancelled",{now:2000}),/version/);assert.equal(value.state,"password_pending");assert.equal(value.cancelledAt,null);});
test("transitions locales utilisent des millisecondes et s'arrêtent devant MFA",()=>{const initial=fixture();assert.throws(()=>transitionActivation(initial,"email_verification_pending",{now:1500}),/preuve serveur/);const password=transitionActivation(initial,"email_verification_pending",{now:1500,serverProof:true});assert.equal(password.passwordCompletedAt,1500);const email=transitionActivation(password,"mfa_enrollment_pending",{now:2000,serverProof:true});assert.equal(email.emailVerifiedAt,2000);assert.throws(()=>transitionActivation(email,"ready_for_activation",{now:2500,serverProof:true}),/MFA réelle/);assert.throws(()=>transitionActivation(email,"completed",{now:2500,serverProof:true}));});
test("expiration matérialise expiredAt et les états terminaux ne rouvrent pas",()=>{const expired=transitionActivation(fixture(),"email_verification_pending",{now:5000,serverProof:true}),cancelled=transitionActivation(fixture(),"cancelled",{now:1500});assert.equal(expired.state,"expired");assert.equal(expired.expiredAt,5000);assert.equal(cancelled.state,"cancelled");assert.equal(cancelled.expiredAt,null);for(const terminal of [expired,cancelled])assert.throws(()=>transitionActivation(terminal,"password_pending",{now:5100,serverProof:true}),/terminale/);});
