import test from "node:test";import assert from "node:assert/strict";
import {assertAuditReadOnly,decodeAuditCursor,encodeAuditCursor,matchesAuditFilters,minimizeAuditEvent,parseAuditQuery,stableAuditSort} from "../../lib/crm/audit-management.mjs";
import {effectivePermissions,GLOBAL_ROLES} from "../../lib/crm/organization-authorization.mjs";
const perms=(roles,status="active")=>effectivePermissions({accountStatus:status,globalRoles:roles,organization:null,membership:null,organizationId:null}).global;
const event=(overrides={})=>({eventId:"event_001",eventType:"contribution.updated",category:"contribution",actorType:"local_admin",actorUid:"admin_001",targetType:"contribution",targetId:"contribution_001",contributionId:"contribution_001",changedFields:["title"],result:"success",occurredAt:{seconds:1,toMillis(){return 1000}},correlationId:"correlation_001",schemaVersion:1,reason:"motif fictif",email:"secret@example.test",storagePath:"private/x",...overrides});
test("audit.read appartient à administrator",()=>assert.ok(perms(["administrator"]).includes("audit.read")));
test("technical_owner seul ne reçoit pas audit.read",()=>assert.ok(!perms(["technical_owner"]).includes("audit.read")));
test("aucun autre rôle global ne reçoit audit.read",()=>{for(const role of Object.keys(GLOBAL_ROLES).filter(r=>!["administrator","technical_owner"].includes(r)))assert.ok(!perms([role]).includes("audit.read"),role)});
test("cumul propriétaire et administrateur autorisé seulement grâce à administrator",()=>assert.ok(perms(["technical_owner","administrator"]).includes("audit.read")));
test("un compte non actif ne reçoit aucune permission",()=>assert.deepEqual(perms(["administrator"],"suspended"),[]));
test("permission locale sans effet sur audit.read",()=>{const value=effectivePermissions({accountStatus:"active",globalRoles:[],organization:{},membership:{},organizationId:"org_001"});assert.ok(!value.organization.includes("audit.read"))});
test("limite par défaut 25",()=>assert.equal(parseAuditQuery().limit,25));
test("limite maximale 100",()=>assert.equal(parseAuditQuery({limit:"100"}).limit,100));
test("limites nulles négatives et excessives refusées",()=>{for(const limit of ["0","-1","101"])assert.throws(()=>parseAuditQuery({limit}))});
test("filtre inconnu refusé",()=>assert.throws(()=>parseAuditQuery({search:"texte"}),/filtre/));
test("catégorie inconnue refusée",()=>assert.throws(()=>parseAuditQuery({category:"finance"}),/catégorie/));
test("résultat inconnu refusé",()=>assert.throws(()=>parseAuditQuery({result:"maybe"}),/résultat/));
test("identifiant invalide refusé",()=>assert.throws(()=>parseAuditQuery({actorUid:"../x"}),/invalide/));
test("période inversée refusée",()=>assert.throws(()=>parseAuditQuery({from:"2026-04-02",to:"2026-04-01"}),/inversée/));
test("période supérieure à 90 jours refusée",()=>assert.throws(()=>parseAuditQuery({from:"2026-01-01",to:"2026-05-01"}),/90/));
test("curseur valide accepté",()=>{const cursor=encodeAuditCursor({eventId:"event_001",occurredAtMillis:1000},{category:"asset"});assert.equal(decodeAuditCursor(cursor,{category:"asset"}).eventId,"event_001")});
test("curseur altéré refusé",()=>{const cursor=encodeAuditCursor({eventId:"event_001",occurredAtMillis:1000});assert.throws(()=>decodeAuditCursor(`${cursor.slice(0,-2)}xx`),/curseur/)});
test("curseur incompatible avec les filtres refusé",()=>{const cursor=encodeAuditCursor({eventId:"event_001",occurredAtMillis:1000},{category:"asset"});assert.throws(()=>decodeAuditCursor(cursor,{category:"security"}),/incompatible/)});
test("tri stable par date puis eventId décroissants",()=>{const values=[event({eventId:"event_001"}),event({eventId:"event_003"}),event({eventId:"event_002",occurredAt:{seconds:2,toMillis(){return 2000}}})].sort(stableAuditSort);assert.deepEqual(values.map(x=>x.eventId),["event_002","event_003","event_001"])});
test("réponse strictement minimisée",()=>{const value=minimizeAuditEvent(event());assert.equal(value.eventId,"event_001");assert.equal("email" in value,false);assert.equal("storagePath" in value,false)});
test("champs sensibles exclus",()=>{const value=minimizeAuditEvent(event({password:"x",token:"x",body:"x",ipAddress:"x"}));for(const key of ["password","token","body","ipAddress"])assert.equal(key in value,false)});
test("previousState et nextState ne sont pas retournés",()=>{const value=minimizeAuditEvent(event({previousState:"a",nextState:"b"}));assert.equal("previousState" in value,false);assert.equal("nextState" in value,false)});
test("filtres exacts correspondent sans recherche libre",()=>{const spec=parseAuditQuery({category:"contribution",result:"success",actorUid:"admin_001"});assert.ok(matchesAuditFilters(event(),spec));assert.ok(!matchesAuditFilters(event({result:"failed"}),spec))});
test("GET est la seule méthode autorisée",()=>{assert.equal(assertAuditReadOnly("GET"),true);for(const method of ["POST","PATCH","PUT","DELETE"])assert.throws(()=>assertAuditReadOnly(method))});
test("aucune fonction de mutation n'est exposée",async()=>{const auditModule=await import("../../lib/crm/audit-management.mjs");assert.ok(!Object.keys(auditModule).some(name=>/create|update|delete|purge|export/i.test(name)))});
