import test from "node:test";import assert from "node:assert/strict";
import {consumeInvitation,createInvitation,generateInvitationToken,invitationTokenFingerprint,revokeInvitation,safeInvitationFingerprintEqual,validateInvitation} from "../../lib/crm/invitation-policy.mjs";
const stamp=value=>({toMillis:()=>value});
const fixture=()=>{const token=generateInvitationToken(),invitation=createInvitation({invitationId:"invite_test",uid:"editor_test",email:"editor@example.test",token,roles:["editorial_manager"],createdBy:"admin_test",createdAt:stamp(1000),expiresAt:stamp(2000)});return {token,invitation};};
test("invitation pending conserve uniquement une empreinte et une fonction approuvée",()=>{const {token,invitation}=fixture();assert.equal(invitation.state,"pending");assert.deepEqual(invitation.roles,["editorial_manager"]);assert.equal(invitation.tokenFingerprint,invitationTokenFingerprint(token));assert.doesNotMatch(JSON.stringify(invitation),new RegExp(token));assert.equal("token" in invitation,false);});
test("invitation valide est à usage unique et le document final ne conserve ni rôle ni empreinte",()=>{const {token,invitation}=fixture(),used=consumeInvitation(invitation,{token,now:stamp(1500)});assert.equal(used.state,"used");assert.equal("roles" in used,false);assert.equal("tokenFingerprint" in used,false);assert.throws(()=>validateInvitation(used,{token,now:stamp(1600)}),/fermée/);});
test("invitation expirée, révoquée ou token incorrect sont refusés",()=>{const {token,invitation}=fixture();assert.throws(()=>validateInvitation(invitation,{token,now:stamp(2000)}),/expirée/);assert.throws(()=>validateInvitation(revokeInvitation(invitation,{now:stamp(1200)}),{token,now:stamp(1300)}),/fermée/);assert.throws(()=>validateInvitation(invitation,{token:generateInvitationToken(),now:stamp(1500)}),/invalide/);});
test("seules les adresses fictives et fonctions fermées sont admises",()=>{const {token}=fixture(),base={invitationId:"invite_bad",uid:"editor_bad",email:"editor@example.test",token,roles:["contributor"],createdBy:"admin_test",createdAt:stamp(1000),expiresAt:stamp(2000)};assert.throws(()=>createInvitation({...base,email:"person@example.com"}),/fictif/);for(const roles of [[],["administrator"],["reviewer","editorial_manager"],["reviewer","reviewer"]])assert.throws(()=>createInvitation({...base,roles}));});
test("comparaison d'empreinte constante refuse formats et valeurs incorrects",()=>{const a=invitationTokenFingerprint(generateInvitationToken()),b=invitationTokenFingerprint(generateInvitationToken());assert.equal(safeInvitationFingerprintEqual(a,a),true);assert.equal(safeInvitationFingerprintEqual(a,b),false);for(const invalid of ["",a.slice(2),"z".repeat(64),null])assert.equal(safeInvitationFingerprintEqual(a,invalid),false);});
