import assert from "node:assert/strict";
import test from "node:test";
import { applicationDefault,deleteApp,initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { Timestamp,getFirestore } from "firebase-admin/firestore";
import { ACTIVATION_FIELDS } from "../../lib/crm/activation-policy.mjs";
import { INVITATION_REJECTED,INVITATION_USED_FIELDS,generateInvitationToken,invitationTokenFingerprint } from "../../lib/crm/invitation-policy.mjs";
import { consumeCrmInvitation,deriveActivationId,validateExactRawActivation } from "../../lib/firebase/invitation-admin.mjs";
import { PROJECT_ID,assertLocalEmulatorSafety } from "./test-helpers.mjs";

async function fixture(label,{role="editorial_manager",emailVerified=false,disabled=true}={}){assertLocalEmulatorSafety();const suffix=`${Date.now()}_${Math.random().toString(36).slice(2)}`,app=initializeApp({projectId:PROJECT_ID,credential:applicationDefault()},`${label}-${suffix}`),auth=getAuth(app),database=getFirestore(app),uid=`user_${suffix}`,email=`${suffix}@example.test`,id=`invite_${suffix}`,token=generateInvitationToken(),invitationRef=database.doc(`crmInvitations/${id}`),activationId=deriveActivationId(id),activationRef=database.doc(`crmActivations/${activationId}`),profileRef=database.doc(`users/${uid}`),createdAt=Timestamp.now();await auth.createUser({uid,email,emailVerified,disabled});await profileRef.set({uid,displayName:"Compte activation fictif",email,status:"invited",globalRoles:[],organizationMemberships:[],createdAt,updatedAt:createdAt,createdBy:"technical_owner_test",updatedBy:"technical_owner_test",version:1});const pending={invitationId:id,uid,email,state:"pending",tokenFingerprint:invitationTokenFingerprint(token),roles:[role],createdBy:"technical_owner_test",createdAt,expiresAt:Timestamp.fromMillis(Date.now()+60_000),usedAt:null,revokedAt:null,version:1};await invitationRef.set(pending);return {app,auth,database,uid,email,id,token,pending,activationId,invitationRef,activationRef,profileRef,async close(){await Promise.all([invitationRef.delete().catch(()=>{}),activationRef.delete().catch(()=>{}),profileRef.delete().catch(()=>{}),auth.deleteUser(uid).catch(()=>{})]);await deleteApp(app);}};}

test("consommation atomique transfère la fonction vers le chemin opaque déterministe sans activer le profil",async()=>{const f=await fixture("activation-atomic");try{const result=await consumeCrmInvitation(f.database,f.auth,f.id,f.token);assert.deepEqual(result,{state:"accepted",activationId:f.activationId,uid:f.uid,email:f.email,version:1});assert.equal(f.activationId,deriveActivationId(f.id));assert.match(f.activationId,/^[a-f0-9]{64}$/);assert.equal([f.email,f.uid,"editorial_manager",f.token].some(value=>f.activationId.includes(value)),false);const invitation=(await f.invitationRef.get()).data(),activation=(await f.activationRef.get()).data(),profile=(await f.profileRef.get()).data(),identity=await f.auth.getUser(f.uid);assert.deepEqual(Object.keys(invitation).sort(),[...INVITATION_USED_FIELDS].sort());assert.equal(invitation.state,"used");assert.equal(invitation.version,2);for(const field of ["roles","token","tokenFingerprint"])assert.equal(field in invitation,false);assert.equal(Object.keys(activation).length,17);assert.deepEqual(Object.keys(activation).sort(),[...ACTIVATION_FIELDS].sort());assert.equal(activation.activationId,f.activationId);assert.equal(activation.invitationId,f.id);assert.equal(activation.expiredAt,null);assert.deepEqual(activation.approvedGlobalRoles,["editorial_manager"]);assert.equal(activation.state,"password_pending");assert.equal(activation.mfaRequired,true);assert.equal(validateExactRawActivation(activation).createdAt,activation.createdAt.toMillis());for(const field of ["password","token","emailActionCode","totpSecret","recoveryCode","cookie","idToken","customClaims","permissions","role"])assert.equal(field in activation,false);assert.equal(profile.status,"invited");assert.deepEqual(profile.globalRoles,[]);assert.equal(profile.version,1);assert.equal(identity.disabled,true);assert.equal(identity.emailVerified,false);assert.equal(JSON.stringify({invitation,activation,profile}).includes(f.token),false);}finally{await f.close();}});

test("deux consommations concurrentes produisent exactement un succès, un refus et un registre",async()=>{const f=await fixture("activation-concurrent");try{const results=await Promise.allSettled([consumeCrmInvitation(f.database,f.auth,f.id,f.token),consumeCrmInvitation(f.database,f.auth,f.id,f.token)]),successes=results.filter(result=>result.status==="fulfilled"),failures=results.filter(result=>result.status==="rejected");assert.equal(successes.length,1);assert.equal(failures.length,1);assert.equal(failures[0].reason.code,INVITATION_REJECTED);assert.equal((await f.activationRef.get()).exists,true);assert.equal((await f.database.collection("crmActivations").where("invitationId","==",f.id).get()).size,1);assert.equal((await f.invitationRef.get()).data().state,"used");const profile=(await f.profileRef.get()).data();assert.equal(profile.status,"invited");assert.deepEqual(profile.globalRoles,[]);}finally{await f.close();}});

test("adaptateur exige chaque Timestamp Admin réel avant projection",()=>{const createdAt=Timestamp.fromMillis(1000),raw={activationId:"a".repeat(64),invitationId:"invitation_test",uid:"user_test",email:"user@example.test",approvedGlobalRoles:["contributor"],state:"password_pending",mfaRequired:true,createdAt,expiresAt:Timestamp.fromMillis(5000),passwordCompletedAt:null,emailVerifiedAt:null,mfaCompletedAt:null,completedAt:null,cancelledAt:null,expiredAt:null,version:1,schemaVersion:1};assert.equal(validateExactRawActivation(raw).createdAt,1000);for(const invalid of [new Date(1000),1000,"1000",{toMillis:()=>1000}])assert.throws(()=>validateExactRawActivation({...raw,createdAt:invalid}),error=>error.code===INVITATION_REJECTED);const missing={...raw};delete missing.expiredAt;assert.throws(()=>validateExactRawActivation(missing),error=>error.code===INVITATION_REJECTED);assert.throws(()=>validateExactRawActivation({...raw,unknown:true}),error=>error.code===INVITATION_REJECTED);});

test("identité Auth absente ou incohérente refuse sans consommation ni registre",async()=>{for(const [label,change] of [["absent",async f=>f.auth.deleteUser(f.uid)],["enabled",async f=>f.auth.updateUser(f.uid,{disabled:false})],["verified",async f=>f.auth.updateUser(f.uid,{emailVerified:true})]]){const f=await fixture(`activation-auth-${label}`);try{await change(f);await assert.rejects(consumeCrmInvitation(f.database,f.auth,f.id,f.token),error=>error.code===INVITATION_REJECTED);assert.deepEqual((await f.invitationRef.get()).data(),f.pending);assert.equal((await f.activationRef.get()).exists,false);}finally{await f.close();}}});

test("profil, invitation et rôles invalides sont refusés sans écriture partielle",async()=>{const variants=[{name:"profile-status",apply:async f=>f.profileRef.update({status:"active"})},{name:"profile-role",apply:async f=>f.profileRef.update({globalRoles:["contributor"]})},{name:"profile-version-missing",apply:async f=>{const raw=(await f.profileRef.get()).data();delete raw.version;await f.profileRef.set(raw);}},{name:"profile-version-zero",apply:async f=>f.profileRef.update({version:0})},{name:"profile-version-negative",apply:async f=>f.profileRef.update({version:-1})},{name:"profile-version-decimal",apply:async f=>f.profileRef.update({version:1.5})},{name:"profile-version-excessive",apply:async f=>f.profileRef.update({version:Number.MAX_SAFE_INTEGER})},{name:"path-content",apply:async f=>f.invitationRef.update({invitationId:"other_invitation"})},{name:"uid",apply:async f=>f.invitationRef.update({uid:"other_user"})},{name:"email",apply:async f=>f.invitationRef.update({email:"other@example.test"})},{name:"expired",apply:async f=>f.invitationRef.update({expiresAt:Timestamp.fromMillis(Date.now()-1)})},{name:"revoked",apply:async f=>f.invitationRef.set({invitationId:f.id,uid:f.uid,email:f.email,state:"revoked",createdBy:"technical_owner_test",createdAt:Timestamp.now(),expiresAt:Timestamp.fromMillis(Date.now()+60_000),usedAt:null,revokedAt:Timestamp.now(),version:2})},{name:"unknown-role",apply:async f=>f.invitationRef.update({roles:["administrator"]})},{name:"duplicate-role",apply:async f=>f.invitationRef.update({roles:["reviewer","reviewer"]})},{name:"empty-role",apply:async f=>f.invitationRef.update({roles:[]})}];for(const variant of variants){const f=await fixture(`activation-invalid-${variant.name}`);try{await variant.apply(f);const before=(await f.invitationRef.get()).data();await assert.rejects(consumeCrmInvitation(f.database,f.auth,f.id,f.token),error=>error.code===INVITATION_REJECTED);assert.deepEqual((await f.invitationRef.get()).data(),before);assert.equal((await f.activationRef.get()).exists,false);}finally{await f.close();}}});

test("champ client ou schéma pending supplémentaire est refusé et reste inchangé",async()=>{for(const [index,extra] of [{role:"reviewer"},{permissions:["member.approve"]},{accountStatus:"active"},{active:true},{token:"raw-token-interdit"},{mfaRequired:false},{unknown:"value"}].entries()){const f=await fixture(`activation-schema-${index}`);try{const raw={...f.pending,...extra};await f.invitationRef.set(raw);await assert.rejects(consumeCrmInvitation(f.database,f.auth,f.id,f.token),error=>error.code===INVITATION_REJECTED&&error.message==="invitation refusée");assert.deepEqual((await f.invitationRef.get()).data(),raw);assert.equal((await f.activationRef.get()).exists,false);}finally{await f.close();}}});
