import assert from "node:assert/strict";
import test from "node:test";
import { applicationDefault,deleteApp,initializeApp } from "firebase-admin/app";
import { Timestamp,getFirestore } from "firebase-admin/firestore";
import { INVITATION_REJECTED,INVITATION_USED_FIELDS,generateInvitationToken,invitationTokenFingerprint } from "../../lib/crm/invitation-policy.mjs";
import { consumeCrmInvitation } from "../../lib/firebase/invitation-admin.mjs";
import { PROJECT_ID,assertLocalEmulatorSafety } from "./test-helpers.mjs";

const pending=(id,token)=>({invitationId:id,uid:"editor_test",email:"editor@example.test",state:"pending",tokenFingerprint:invitationTokenFingerprint(token),roles:[],createdBy:"admin_test",createdAt:Timestamp.now(),expiresAt:Timestamp.fromMillis(Date.now()+60_000),usedAt:null,revokedAt:null,version:1});
test("deux consommations concurrentes produisent une transition et un rejet métier fermé",async()=>{assertLocalEmulatorSafety();const app=initializeApp({projectId:PROJECT_ID,credential:applicationDefault()},`invitation-${Date.now()}`),database=getFirestore(app),id=`invite_${Date.now()}_${Math.random().toString(36).slice(2)}`,ref=database.doc(`crmInvitations/${id}`),token=generateInvitationToken();try{await ref.set(pending(id,token));const results=await Promise.allSettled([consumeCrmInvitation(database,id,token),consumeCrmInvitation(database,id,token)]),successes=results.filter(result=>result.status==="fulfilled"),failures=results.filter(result=>result.status==="rejected");assert.equal(successes.length,1);assert.equal(failures.length,1);assert.equal(failures[0].reason.code,INVITATION_REJECTED);const final=(await ref.get()).data();assert.deepEqual(Object.keys(final).sort(),[...INVITATION_USED_FIELDS].sort());assert.equal(final.state,"used");assert.equal(final.version,2);assert.equal(final.usedAt instanceof Timestamp,true);for(const field of ["role","roles","permissions","accountStatus","active","token","tokenFingerprint"])assert.equal(field in final,false);assert.equal(JSON.stringify(final).includes(token),false);}finally{await ref.delete().catch(()=>{});await deleteApp(app);}});

test("invitations pending hors schéma sont refusées sans aucune écriture",async()=>{assertLocalEmulatorSafety();const app=initializeApp({projectId:PROJECT_ID,credential:applicationDefault()},`invitation-schema-${Date.now()}`),database=getFirestore(app),token=generateInvitationToken();try{for(const [index,extra] of [{role:"reviewer"},{permissions:["member.approve"]},{accountStatus:"active"},{active:true},{token},{unknown:"value"}].entries()){const id=`invite_schema_${Date.now()}_${index}`,ref=database.doc(`crmInvitations/${id}`),raw={...pending(id,token),...extra};await ref.set(raw);await assert.rejects(consumeCrmInvitation(database,id,token),error=>error.code===INVITATION_REJECTED&&error.message==="invitation refusée");const final=(await ref.get()).data();assert.deepEqual(final,raw);await ref.delete();}}finally{await deleteApp(app);}});
