import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { MEMBERSHIP_DETECTION_LIMIT, MEMBERSHIP_QUOTA_MAX, MembershipQuotaError, membershipQuotaDelta, nextMembershipQuota, occupiesMembershipSlot, validateAuthoritativeMemberships } from "../../lib/crm/membership-quota.mjs";

const now = { seconds: 1 }, uid = "quota-user";
const membership = (organizationId, status = "active", overrides = {}) => ({ organizationId, uid, roles: [], status, createdAt: now, updatedAt: now, createdBy: "quota-admin", updatedBy: "quota-admin", version: 1, ...overrides });
const entry = (index, status = "active", overrides = {}) => ({ id: uid, path: `organizations/org-${String(index).padStart(3, "0")}/memberships/${uid}`, data: membership(`org-${String(index).padStart(3, "0")}`, status, overrides) });
const quota = occupiedSlots => ({ uid, occupiedSlots, schemaVersion: 1, createdAt: now, updatedAt: now, version: 1 });
const code = (expected, operation) => assert.throws(operation, error => error instanceof MembershipQuotaError && error.code === expected);

test("les constantes canoniques valent 50 et 51", () => { assert.equal(MEMBERSHIP_QUOTA_MAX, 50); assert.equal(MEMBERSHIP_DETECTION_LIMIT, 51); });
test("invited, active et suspended occupent; revoked libère", () => { for (const status of ["invited", "active", "suspended"]) assert.equal(occupiesMembershipSlot(status), true); assert.equal(occupiesMembershipSlot("revoked"), false); });
test("les deltas couvrent créations, transitions, rôles et révocations", () => { assert.equal(membershipQuotaDelta(undefined, "invited"), 1); assert.equal(membershipQuotaDelta(undefined, "active"), 1); assert.equal(membershipQuotaDelta("revoked", "invited"), 1); assert.equal(membershipQuotaDelta("revoked", "active"), 1); assert.equal(membershipQuotaDelta("invited", "active"), 0); assert.equal(membershipQuotaDelta("active", "suspended"), 0); assert.equal(membershipQuotaDelta("suspended", "active"), 0); for (const status of ["invited", "active", "suspended"]) assert.equal(membershipQuotaDelta(status, "revoked"), -1); assert.equal(membershipQuotaDelta("active", "active"), 0); });
test("0 à 50 appartenances cohérentes sont acceptées dans un ordre déterministe", () => { assert.deepEqual(validateAuthoritativeMemberships(uid, [], null), []); for (const count of [1, 25, 50]) { const values = Array.from({ length: count }, (_, index) => entry(count - index - 1)); const result = validateAuthoritativeMemberships(uid, values, quota(count)); assert.equal(result.length, count); assert.deepEqual(result.map(item => item.path), [...result.map(item => item.path)].sort()); } });
test("51 appartenances échouent sans résultat partiel", () => code("too-many-memberships", () => validateAuthoritativeMemberships(uid, Array.from({ length: 51 }, (_, index) => entry(index)), quota(50))));
test("quota absent, négatif, supérieur ou différent échoue fermé", () => { code("quota-missing", () => validateAuthoritativeMemberships(uid, [entry(1)], null)); code("quota-inconsistent", () => validateAuthoritativeMemberships(uid, [], quota(-1))); code("quota-inconsistent", () => validateAuthoritativeMemberships(uid, [], quota(51))); code("quota-inconsistent", () => validateAuthoritativeMemberships(uid, [entry(1)], quota(0))); });
test("document mal formé, UID incohérent et doublon échouent fermé", () => { code("membership-malformed", () => validateAuthoritativeMemberships(uid, [entry(1, "active", { roles: ["unknown"] })], quota(1))); code("membership-malformed", () => validateAuthoritativeMemberships(uid, [entry(1, "active", { uid: "other-user" })], quota(1))); code("membership-duplicate", () => validateAuthoritativeMemberships(uid, [entry(1), { ...entry(1), path: `organizations/duplicate/memberships/${uid}` }], quota(2))); });
test("le plafond refuse 50 vers 51 et un compteur nul ne décrémente pas", () => { code("quota-exceeded", () => nextMembershipQuota(quota(50), uid, 1, now)); code("quota-inconsistent", () => nextMembershipQuota(quota(0), uid, -1, now)); assert.equal(nextMembershipQuota(quota(49), uid, 1, now).occupiedSlots, 50); });
test("une répétition sans changement ne modifie ni compteur ni version", () => { const current = quota(12), next = nextMembershipQuota(current, uid, 0, now); assert.equal(next.occupiedSlots, 12); assert.equal(next.version, 1); });
test("custom claims et projection ne font pas partie du modèle de quota", () => { assert.equal("customClaims" in quota(0), false); assert.equal("organizationMemberships" in quota(0), false); });
test("la seule lecture globale est centralisée, filtrée, ordonnée et bornée", async () => { const files = ["app/api/auth/session/route.ts", "lib/firebase/session.ts", "lib/firebase/organization-admin.ts", "lib/firebase/contribution-admin.ts", "lib/firebase/asset-admin.ts"]; for (const file of files) assert.doesNotMatch(await readFile(new URL(`../../${file}`, import.meta.url), "utf8"), /collectionGroup\(["']memberships["']\)/); const helper = await readFile(new URL("../../lib/firebase/membership-quota-admin.ts", import.meta.url), "utf8"); assert.match(helper, /where\("status","in"/); assert.match(helper, /orderBy\(FieldPath\.documentId\(\)\)/); assert.match(helper, /limit\(MEMBERSHIP_DETECTION_LIMIT\)/); });
