import assert from "node:assert/strict";
import test from "node:test";
import { PRIVATE_RESPONSE_HEADERS, assertFetchMetadata, assertLocalHost, assertLocalOrigin, assertNoPermissiveCors, rejectInexactFilters, validateRequestSecurity } from "../../lib/crm/request-security.mjs";

const read = (overrides = {}) => ({ kind: "read", method: "GET", host: "localhost:3100", origin: null, ...overrides });
const mutation = (overrides = {}) => ({ kind: "mutation", method: "POST", host: "127.0.0.1:3100", origin: "http://127.0.0.1:3100", csrfHeader: "token", csrfCookie: "token", contentType: "application/json", contentLength: 20, maxBytes: 16_384, ...overrides });

test("Host local exact est autorisé", () => { assert.equal(assertLocalHost("localhost:3100"), "localhost:3100"); assert.equal(assertLocalHost("127.0.0.1:3100"), "127.0.0.1:3100"); });
test("Host absent, inconnu, ambigu, trompeur ou mauvais port est refusé", () => { for (const host of [null, "", "localhost", "localhost:3000", "localhost:3100.evil.test", "evil-localhost:3100", "user@localhost:3100", "localhost:3100,evil.test"]) assert.throws(() => assertLocalHost(host)); });
test("X-Forwarded-Host est accepté seulement s'il est strictement identique au Host local", () => { assert.equal(assertLocalHost("localhost:3100", "localhost:3100"), "localhost:3100"); for (const forwarded of ["evil.test", "localhost:3100,evil.test", "127.0.0.1:3100"]) assert.throws(() => assertLocalHost("localhost:3100", forwarded)); });
test("Origin exacte est autorisée et l'absence est compatible avec GET", () => { assert.equal(assertLocalOrigin("http://localhost:3100", "localhost:3100", { required: true }), "http://localhost:3100"); assert.equal(assertLocalOrigin(null, "localhost:3100", { required: false }), null); });
test("Origin absente, null, étrangère ou trompeuse est refusée pour mutation", () => { for (const origin of [null, "null", "https://localhost:3100", "http://evil.test", "http://localhost:3100.evil.test", "http://user@localhost:3100"]) assert.throws(() => assertLocalOrigin(origin, "localhost:3100", { required: true })); });
test("Fetch Metadata same-origin est accepté, cross-site refusé et absence compatible", () => { assert.ok(assertFetchMetadata({ site: "same-origin", mode: "cors", destination: "empty" })); assert.ok(assertFetchMetadata({})); assert.throws(() => assertFetchMetadata({ site: "cross-site" })); });
test("mutation exige Origin, CSRF, JSON et taille bornée", () => { assert.ok(validateRequestSecurity(mutation())); assert.throws(() => validateRequestSecurity(mutation({ origin: null }))); assert.throws(() => validateRequestSecurity(mutation({ csrfHeader: null }))); assert.throws(() => validateRequestSecurity(mutation({ contentType: "text/plain" }))); assert.throws(() => validateRequestSecurity(mutation({ contentLength: 20_000 }))); });
test("méthodes incompatibles sont refusées", () => { assert.throws(() => validateRequestSecurity(read({ method: "POST" }))); assert.throws(() => validateRequestSecurity(mutation({ method: "GET" }))); });
test("filtres post-lecture inexactement paginables sont refusés en HTTP 400", () => { assert.ok(rejectInexactFilters({ limit: "25", cursor: "abc" })); assert.throws(() => rejectInexactFilters({ status: "active" }), error => error.http === 400); });
test("en-têtes privés complets sans HSTS ni CORS permissif", () => { for (const name of ["Cache-Control", "X-Content-Type-Options", "Referrer-Policy", "Permissions-Policy", "Cross-Origin-Opener-Policy", "Content-Security-Policy"]) assert.ok(PRIVATE_RESPONSE_HEADERS[name]); assert.match(PRIVATE_RESPONSE_HEADERS["Content-Security-Policy"], /frame-ancestors 'none'/); assert.equal("Strict-Transport-Security" in PRIVATE_RESPONSE_HEADERS, false); assert.ok(assertNoPermissiveCors(PRIVATE_RESPONSE_HEADERS)); });
