import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { FieldPath, Timestamp } from "firebase-admin/firestore";
import { getLocalAdminServices } from "../../scripts/firebase/local-account-admin.mjs";
import { assertLocalEmulatorSafety } from "./test-helpers.mjs";

const apiFiles = [
  "app/api/crm/accounts/route.ts", "app/api/crm/assets/deletion-requests/route.ts", "app/api/crm/audit-logs/route.ts", "app/api/crm/contributions/route.ts", "app/api/crm/contributions/[contributionId]/assets/route.ts", "app/api/crm/contributions/[contributionId]/assets/[assetId]/download/route.ts", "app/api/crm/organizations/route.ts", "app/api/crm/organizations/[organizationId]/memberships/route.ts",
];
test("chaque GET privé applique la politique centrale", async () => { for (const file of apiFiles) { const source = await readFile(new URL(`../../${file}`, import.meta.url), "utf8"); assert.match(source, /validateCrmRead\(request\)/, file); assert.match(source, /requireCrmActor|actor\(/, file); } });
test("chaque mutation CRM applique CSRF via la politique centrale", async () => { const files = (await Promise.all(["accounts/[uid]", "accounts", "contributions/[contributionId]", "contributions", "organizations/[organizationId]", "organizations/[organizationId]/memberships/[uid]", "organizations/[organizationId]/memberships"].map(async path => [path, await readFile(new URL(`../../app/api/crm/${path}/route.ts`, import.meta.url), "utf8")]))); for (const [path, source] of files) assert.match(source, /validateCrmMutation\(request\)/, path); });
test("pagination filtrée en mémoire supprimée des cinq chargeurs", async () => { for (const file of ["lib/firebase/account-admin.ts", "lib/firebase/organization-admin.ts", "lib/firebase/contribution-admin.ts", "lib/firebase/audit-admin.ts"]) { const source = await readFile(new URL(`../../${file}`, import.meta.url), "utf8"); assert.doesNotMatch(source, /docs\.filter\(|page\.filter\(/, file); } });
test("CSP locale n'autorise ni wildcard connect-src, ni unsafe-eval, ni HSTS", async () => { const source = await readFile(new URL("../../next.config.ts", import.meta.url), "utf8"); assert.match(source, /frame-ancestors 'none'/); assert.doesNotMatch(source, /connect-src \*|unsafe-eval|Strict-Transport-Security/); assert.match(source, /127\.0\.0\.1:9099/); });
test("aucune modification Rules, index, dépendance ou CORS permissif", async () => { const request = await readFile(new URL("../../lib/crm/request-security.mjs", import.meta.url), "utf8"); assert.doesNotMatch(request, /Access-Control-Allow-Origin["']?\s*:\s*["']\*/); });
test("les requêtes autoritatives auteur et relecteur sont servies sans nouvel index", async () => { assertLocalEmulatorSafety(); const { database } = getLocalAdminServices(), prefix = "security-query-", batch = database.batch(); try { for (let index = 0; index < 4; index++) batch.set(database.doc(`contributions/${prefix}${index}`), { authorUid: index < 2 ? "author-local" : "other-local", assignedReviewerUids: index % 2 ? ["reviewer-local"] : [], createdAt: Timestamp.now() }); await batch.commit(); const author = await database.collection("contributions").where("authorUid", "==", "author-local").orderBy(FieldPath.documentId()).limit(3).get(), reviewer = await database.collection("contributions").where("assignedReviewerUids", "array-contains", "reviewer-local").orderBy(FieldPath.documentId()).limit(3).get(); assert.equal(author.size, 2); assert.equal(reviewer.size, 2); } finally { const snapshots = await database.collection("contributions").get(), cleanup = database.batch(); snapshots.docs.filter(doc => doc.id.startsWith(prefix)).forEach(doc => cleanup.delete(doc.ref)); await cleanup.commit(); } });
