import assert from "node:assert/strict";
import test from "node:test";
import { applicationDefault,deleteApp,initializeApp } from "firebase-admin/app";
import { Timestamp,getFirestore } from "firebase-admin/firestore";
import { createSessionRecord } from "../../lib/crm/session-policy.mjs";
import { incrementCrmSessionVersion,issueRegisteredSession,readCrmSessionAuthorization,registerCrmSessionRecord,revokeProviderTokens,validateRegisteredSession } from "../../lib/firebase/session-registry.mjs";
import { PROJECT_ID,assertLocalEmulatorSafety } from "./test-helpers.mjs";

async function fixture(name){assertLocalEmulatorSafety();const suffix=`${Date.now()}_${Math.random().toString(36).slice(2)}`,app=initializeApp({projectId:PROJECT_ID,credential:applicationDefault()},`${name}-${suffix}`),database=getFirestore(app),uid=`user_${suffix}`,profileRef=database.doc(`users/${uid}`);await profileRef.set({uid,email:`${suffix}@example.test`,status:"active",globalRoles:["contributor"],version:1});return {app,database,uid,profileRef,async close(){const sessions=await database.collection("crmSessions").where("uid","==",uid).get();await Promise.all(sessions.docs.map(document=>document.ref.delete()));await profileRef.delete().catch(()=>{});await deleteApp(app);}};}
function record(cookie,uid,version=1){const createdAt=Timestamp.now();return createSessionRecord({cookie,uid,sessionVersion:version,createdAt,expiresAt:Timestamp.fromMillis(createdAt.toMillis()+60_000)});}
async function resolve(database,cookie,uid){const value=record(cookie,uid);return readCrmSessionAuthorization(database,{uid,sessionId:value.sessionId,validate:(profile,stored)=>validateRegisteredSession({cookie,decoded:{uid},profile,record:stored,nowMs:Date.now()})});}

test("création validée puis révocation conserve et invalide le registre",async()=>{const f=await fixture("created-first"),cookie="cookie-session-created-first-123456789";try{const value=record(cookie,f.uid);await registerCrmSessionRecord(f.database,value);assert.equal((await f.database.doc(`crmSessions/${value.sessionId}`).get()).exists,true);assert.equal((await resolve(f.database,cookie,f.uid)).version,1);await incrementCrmSessionVersion(f.database,{uid:f.uid,actorUid:"admin_test",now:Timestamp.now()});assert.equal((await f.database.doc(`crmSessions/${value.sessionId}`).get()).exists,true);await assert.rejects(resolve(f.database,cookie,f.uid),error=>error.code==="ERR_ASSERTION"&&/obsolète/.test(error.message));}finally{await f.close();}});
test("révocation avant création refuse exactement sans document ni cookie",async()=>{const f=await fixture("revoked-first"),cookie="cookie-session-revoked-first-123456789",value=record(cookie,f.uid);try{await incrementCrmSessionVersion(f.database,{uid:f.uid,actorUid:"admin_test",now:Timestamp.now()});let setCookie=null;await assert.rejects(issueRegisteredSession({createCookie:async()=>cookie,register:async candidate=>{await registerCrmSessionRecord(f.database,value);setCookie=candidate;}}),error=>error.code==="SESSION_VERSION_MISMATCH");assert.equal(setCookie,null);assert.equal((await f.database.doc(`crmSessions/${value.sessionId}`).get()).exists,false);}finally{await f.close();}});
test("suspension avant création refuse exactement sans document ni cookie",async()=>{const f=await fixture("suspended-first"),cookie="cookie-session-suspended-first-123456",value=record(cookie,f.uid);try{await f.database.runTransaction(async tx=>{await tx.get(f.profileRef);tx.update(f.profileRef,{status:"suspended",version:2});});let setCookie=null;await assert.rejects(issueRegisteredSession({createCookie:async()=>cookie,register:async candidate=>{await registerCrmSessionRecord(f.database,value);setCookie=candidate;}}),error=>error.code==="SESSION_PROFILE_INVALID");assert.equal(setCookie,null);assert.equal((await f.database.doc(`crmSessions/${value.sessionId}`).get()).exists,false);}finally{await f.close();}});
test("révocation globale invalide exactement deux navigateurs",async()=>{const f=await fixture("two-browsers"),cookies=["cookie-session-browser-one-123456789","cookie-session-browser-two-123456789"];try{for(const cookie of cookies)await registerCrmSessionRecord(f.database,record(cookie,f.uid));for(const cookie of cookies)assert.equal((await resolve(f.database,cookie,f.uid)).version,1);await incrementCrmSessionVersion(f.database,{uid:f.uid,actorUid:"admin_test",now:Timestamp.now()});const results=await Promise.allSettled(cookies.map(cookie=>resolve(f.database,cookie,f.uid)));assert.deepEqual(results.map(result=>result.status),["rejected","rejected"]);assert.equal((await f.database.collection("crmSessions").where("uid","==",f.uid).get()).size,2);}finally{await f.close();}});
test("échec fournisseur ne restaure jamais la version déjà commitée",async()=>{const f=await fixture("provider-failure"),cookie="cookie-session-provider-failure-123456",value=record(cookie,f.uid);try{await registerCrmSessionRecord(f.database,value);await incrementCrmSessionVersion(f.database,{uid:f.uid,actorUid:"admin_test",now:Timestamp.now()});await assert.rejects(revokeProviderTokens(async()=>{throw new Error("panne fictive");},f.uid),error=>error.code==="SESSION_PROVIDER_REVOCATION_FAILED");assert.equal((await f.profileRef.get()).data().version,2);await assert.rejects(resolve(f.database,cookie,f.uid),error=>error.code==="ERR_ASSERTION"&&/obsolète/.test(error.message));}finally{await f.close();}});

test("adaptateur refuse chaque document de session brut hors schéma sans autorisation",async()=>{const f=await fixture("raw-schema"),cookie="cookie-session-raw-schema-123456789",canonical=record(cookie,f.uid),ref=f.database.doc(`crmSessions/${canonical.sessionId}`);try{const malformed=[...['role','globalRoles','permissions','email','cookie','token','customClaims'].map(field=>({...canonical,[field]:field})),{...canonical,unknown:true},Object.fromEntries(Object.entries(canonical).filter(([field])=>field!=="schemaVersion")),{...canonical,schemaVersion:2}];for(const raw of malformed){await ref.set(raw);let authorized=false;await assert.rejects(readCrmSessionAuthorization(f.database,{uid:f.uid,sessionId:canonical.sessionId,validate:()=>{authorized=true;}}),error=>error.code==="SESSION_SCHEMA_INVALID"&&error.message==="session refusée");assert.equal(authorized,false);assert.deepEqual((await ref.get()).data(),raw);} }finally{await f.close();}});

test("création refuse le champ supplémentaire malgré des Timestamp valides et ne persiste rien",async()=>{const f=await fixture("raw-create"),cookie="cookie-session-raw-create-123456789",canonical=record(cookie,f.uid),raw={...canonical,email:"forbidden@example.test"};try{await assert.rejects(registerCrmSessionRecord(f.database,raw),error=>error.code==="SESSION_SCHEMA_INVALID"&&error.message==="session refusée");assert.equal((await f.database.doc(`crmSessions/${canonical.sessionId}`).get()).exists,false);}finally{await f.close();}});
