import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import SiteFooter from "@/components/layout/SiteFooter";
import SiteHeaderClient from "@/components/layout/SiteHeaderClient";

export const metadata: Metadata = { title: "JCAM — Judo Club Ath Mesbah", description: "L’histoire du JCAM, fondé en 1996 : formation, salle Taqaats et titres régionaux, nationaux et continentaux.", alternates: { canonical: "/jcam" } };

const milestones = [
  ["1996", "Fondation du JCAM", "Le Judo Club Ath Mesbah voit le jour avec l’ambition d’offrir aux enfants du village une pratique sportive exigeante et formatrice."],
  ["Sept. 1996", "Les premiers entraînements", "Les premiers judokas montent sur le tatami. Une aventure collective commence, portée par l’apprentissage et la régularité."],
  ["2000 — 2001", "Les premiers titres régionaux", "Le travail de formation se traduit par les premières consécrations régionales du club."],
  ["2005", "Les premiers titres nationaux", "Des athlètes formés au JCAM atteignent le niveau national et inscrivent le nom du club au-delà de la région."],
  ["2006", "Les premiers titres continentaux", "Une nouvelle étape est franchie avec des résultats à l’échelle continentale."],
  ["Aujourd’hui", "Former la prochaine génération", "Le club poursuit sa mission auprès des jeunes, entre pratique quotidienne, compétitions et transmission."],
] as const;

const values = [["Respect", "Considérer son partenaire, son enseignant, les règles et le lieu de pratique."], ["Discipline", "Progresser par la régularité, l’écoute et la maîtrise de soi."], ["Courage", "Accepter la chute, faire face à la difficulté et recommencer."], ["Transmission", "Recevoir une expérience puis accompagner à son tour les plus jeunes."]] as const;
const levels = [["2000 — 2001", "Régional", "Premières consécrations"], ["2005", "National", "Un nouveau cap franchi"], ["2006", "Continental", "Le JCAM au-delà des frontières"]] as const;

export default function JcamPage() {
  return <><a className="skip-link" href="#contenu-principal">Aller au contenu principal</a><SiteHeaderClient/><main id="contenu-principal" className="jcam-page jcam-premium" tabIndex={-1}>
    <header className="jcam-hero jcam-premium-hero"><div className="jcam-hero-copy"><p className="eyebrow light">Judo Club Ait Mesbah · depuis 1996</p><h1>JCAM</h1><p>Une école de judo née au village, où l’on apprend à tomber, à se relever et à grandir ensemble.</p><div className="jcam-hero-actions"><a href="#histoire">Découvrir l’histoire <span aria-hidden="true">↓</span></a><Link href="/contribuer?category=photographs_archives&title=Archive du JCAM#envoyer">Confier une archive</Link><a href="https://www.facebook.com/JUDOJCAM96" target="_blank" rel="noreferrer">Facebook <span aria-hidden="true">↗</span></a></div></div><figure className="jcam-hero-crest"><div><Image src="/images/jcam-logo.png" alt="Logo officiel noir et jaune du Judo Club Ait Mesbah, fondé en 1996" fill priority sizes="(max-width: 700px) 66vw, 390px"/></div><figcaption><span>Emblème officiel</span><strong>Judo Club Ait Mesbah · 1996</strong></figcaption></figure><span className="jcam-hero-year" aria-hidden="true">96</span></header>

    <nav className="jcam-toc" aria-label="Sommaire"><span>Parcourir la page</span><ol><li><a href="#histoire"><span>01</span>Histoire</a></li><li><a href="#chronologie"><span>02</span>Chronologie</a></li><li><a href="#formation"><span>03</span>Formation</a></li><li><a href="#taqaats"><span>04</span>Taqaats</a></li><li><a href="#palmares"><span>05</span>Palmarès</a></li><li><a href="#archives"><span>06</span>Archives</a></li></ol></nav>

    <section id="histoire" className="jcam-origin jcam-premium-origin"><div><p className="eyebrow">L’esprit des débuts</p><h2>Un club fondé pour former, éduquer et ouvrir des horizons</h2><span className="jcam-origin-date">1996</span></div><div><p className="jcam-lead">Fondé en 1996, le JCAM a installé le judo au cœur de la vie sportive d’Aït Mesbah. Dès septembre, les premiers entraînements donnent naissance à une école exigeante et profondément collective.</p><p>Sur le tatami, les enfants découvrent une discipline complète : technique, maîtrise de soi, confiance, respect du partenaire et goût de l’effort. Autour d’eux, entraîneurs, dirigeants, familles et bénévoles rendent cette continuité possible.</p><p>Quelques années suffisent pour que le travail patient du club produise ses premiers résultats régionaux, avant les consécrations nationales puis continentales.</p><aside>Les noms des fondateurs, premiers encadrants et athlètes seront publiés à mesure que les archives et témoignages auront été recueillis puis vérifiés.</aside></div></section>

    <section id="chronologie" className="jcam-premium-timeline"><header><p className="eyebrow">Repères du club</p><h2>De la naissance du dojo<br/><em>aux premiers grands titres</em></h2></header><ol>{milestones.map(([date,title,text], index) => <li key={date}><span>{String(index + 1).padStart(2,"0")}</span><time>{date}</time><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>

    <section id="formation" className="jcam-values jcam-premium-values"><div className="jcam-heading"><p className="eyebrow light">La voie du judo</p><h2>Former des athlètes.<br/>Faire grandir des personnes.</h2><p>La victoire compte, mais elle ne résume pas le travail du club. Le JCAM transmet une manière de progresser avec les autres et de porter dignement les couleurs du village.</p></div><div className="jcam-values-grid">{values.map(([title,text], index) => <article key={title}><span>{String(index + 1).padStart(2,"0")}</span><i aria-hidden="true">{index === 0 ? "礼" : index === 1 ? "律" : index === 2 ? "勇" : "伝"}</i><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section id="taqaats" className="jcam-premium-dojo"><figure><Image src="/images/jcam-jeunes-taqaats.jpg" alt="Jeunes judokas du JCAM réunis dans la salle Taqaats" fill sizes="(max-width: 900px) 100vw, 58vw"/><figcaption><span>La relève du JCAM</span><strong>Une génération réunie sur le tatami</strong></figcaption></figure><div><p className="eyebrow">Le cœur du club</p><h2>La salle<br/>Taqaats</h2><p className="jcam-lead">Plus qu’un équipement sportif, Taqaats est un lieu d’apprentissage, de rencontres et de souvenirs partagés.</p><p>Les gestes s’y répètent, les grades s’y préparent et les plus jeunes y découvrent les règles de la vie collective. Chaque entraînement ajoute une page à l’histoire du club.</p><dl><div><dt>On y apprend</dt><dd>Technique · respect · maîtrise</dd></div><div><dt>On y construit</dt><dd>Confiance · amitié · continuité</dd></div></dl></div></section>

    <section id="palmares" className="jcam-honours jcam-premium-honours"><header className="jcam-heading"><p className="eyebrow light">L’excellence par la formation</p><h2>Du village<br/><em>aux podiums</em></h2><p>Les résultats racontent une progression : d’abord régionale, puis nationale, enfin continentale. Derrière chaque titre se trouvent des années d’entraînement et une communauté mobilisée.</p></header><div className="jcam-levels">{levels.map(([year,level,note], index) => <article key={level}><span>{String(index + 1).padStart(2,"0")}</span><time>{year}</time><strong>{level}</strong><small>{note}</small></article>)}</div><p className="jcam-honours-note">Le palmarès nominatif sera constitué à partir des résultats officiels, diplômes, photographies et témoignages vérifiés transmis par le club et les familles.</p></section>

    <section id="archives" className="jcam-premium-gallery"><header><div><p className="eyebrow">Le club aujourd’hui</p><h2>Une histoire portée<br/>par ses athlètes</h2></div><p>En compétition comme à l’entraînement, le groupe raconte une même exigence : progresser ensemble et représenter dignement le club.</p></header><div className="jcam-gallery-grid jcam-gallery-single"><figure><Image src="/images/jcam-athletes-competition.jpg" alt="Athlètes du JCAM réunis lors d’une compétition" fill sizes="(max-width: 800px) 100vw, 72vw"/><figcaption><span>Compétition · génération actuelle</span><strong>Le collectif avant le combat</strong></figcaption></figure><aside><span>Suivre le club</span><h3>Le JCAM<br/>au quotidien</h3><p>Actualités, compétitions, résultats et vie du club sont également publiés sur sa page officielle.</p><a href="https://www.facebook.com/JUDOJCAM96" target="_blank" rel="noreferrer">Ouvrir la page Facebook <b aria-hidden="true">↗</b></a></aside></div></section>

    <section className="jcam-transmission jcam-premium-final"><p className="eyebrow">1996 — demain</p><h2>Préserver l’histoire.<br/><em>Préparer la relève.</em></h2><p>Photographies, résultats, licences, affiches, récits d’entraîneurs ou souvenirs de compétition : chaque trace peut compléter l’histoire collective du JCAM.</p><div><Link className="primary" href="/contribuer?category=photographs_archives&title=Archive ou témoignage du JCAM#envoyer">Enrichir les archives du club <span aria-hidden="true">↗</span></Link><a href="https://www.facebook.com/JUDOJCAM96" target="_blank" rel="noreferrer">Suivre le JCAM</a><Link href="/vivre">Retour à la vie du village</Link></div></section>
  </main><SiteFooter/></>;
}
