import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {crafts} from "@/data/crafts";
import {CraftDrawing} from "@/components/home/CraftSection";
import SiteHeaderClient from "@/components/layout/SiteHeaderClient";
import SiteFooter from "@/components/layout/SiteFooter";
import PotteryPhotoCollection from "@/components/archives/PotteryPhotoCollection";
import ImageArchiveViewer from "@/components/archives/ImageArchiveViewer";
import "../artisanat.css";

export function generateStaticParams(){return crafts.map(craft=>({metier:craft.slug}));}
export async function generateMetadata({params}:{params:Promise<{metier:string}>}):Promise<Metadata>{const {metier}=await params;const craft=crafts.find(item=>item.slug===metier);return craft?{title:`${craft.name} — Artisanat d’Aït Mesbah`,description:craft.summary,alternates:{canonical:`/artisanat/${craft.slug}`}}:{};}
export default async function MetierPage({params}:{params:Promise<{metier:string}>}){
  const {metier}=await params;const craft=crafts.find(item=>item.slug===metier);if(!craft)notFound();
  return <><SiteHeaderClient/><main className="craft-page" id="contenu-principal"><header className="craft-hero craft-detail-hero"><Link className="craft-back" href="/artisanat">← Artisanat & savoir-faire</Link><p className="craft-label">{craft.number} · {craft.material}</p><h1>{craft.name}</h1><p className="craft-subtitle">{craft.subtitle}</p><p>{craft.summary}</p><div className="craft-detail-drawing"><CraftDrawing kind={craft.slug}/></div></header>
  <nav className="craft-chapters" aria-label="Dans cette page">{craft.sections.map(([title],index)=><a href={`#chapitre-${index+1}`} key={title}><span>0{index+1}</span>{title}<span aria-hidden="true">↓</span></a>)}{metier === "poterie" && <><a href="#photographies-1939"><span>04</span>Les photographies de 1939<span aria-hidden="true">↓</span></a><a href="#archives-1990"><span>05</span>Archives des potières (1990)<span aria-hidden="true">↓</span></a></>}</nav>
  {metier === "poterie" && <PotteryPhotoCollection />}
  {metier === "poterie" && <section className="craft-sources" id="archives-1990"><p className="craft-label">Archives photographiques · Début des années 1990</p><h2>Les potières d’Aït Mesbah à l’apogée de l’Association Imache Amar.</h2><p>Prises au début des années 1990 pendant la période florissante de l’Association Culturelle Imache Amar d’Aït Mesbah, ces deux photographies d’archives immortalisent le travail passionné et la transmission du patrimoine de la poterie au village.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "2rem", margin: "2rem 0" }}><div><ImageArchiveViewer src="/archives/poterie-1990/madame-haouili-potiere-1990.jpg" alt="Madame Haouili peignant une jarre d'argile" title="Madame Haouili peignant une jarre" aspectRatio="1 / 1" /><h3 style={{ fontSize: "1.25rem", marginTop: "1rem" }}>Madame Haouili</h3><p style={{ fontSize: "0.95rem", color: "var(--color-text-muted)" }}>Potière appliquant les engobes rouges à l’aide d’un pinceau sur les motifs d’une jarre en terre cuite.</p><Link className="craft-link" href="/histoire-memoire/archives/potiere-haouili-1990">Consulter la fiche d’archive de Mme Haouili <span aria-hidden="true">→</span></Link></div><div><ImageArchiveViewer src="/archives/poterie-1990/madame-guernine-poterie-1990.jpg" alt="Madame Guernine posant près de grands objets artisanaux et akufi" title="Madame Guernine au milieu des objets artisanaux" aspectRatio="1 / 1" /><h3 style={{ fontSize: "1.25rem", marginTop: "1rem" }}>Madame Guernine</h3><p style={{ fontSize: "0.95rem", color: "var(--color-text-muted)" }}>Doyenne posant en tenue traditionnelle auprès d’un grand Akufi peint et de pichets artisanaux.</p><Link className="craft-link" href="/histoire-memoire/archives/madame-guernine-1990">Consulter la fiche d’archive de Mme Guernine <span aria-hidden="true">→</span></Link></div></div><p><strong>Source :</strong> Archives de l’Association Culturelle Imache Amar d’Aït Mesbah · Début des années 1990.</p></section>}
  {metier === "poterie" && <section className="craft-sources" id="retour-des-champs-1966"><p className="craft-label">Les objets dans la vie quotidienne · 1966</p><h2>Retour des champs, à Tharkavthe.</h2><p>Cette scène pastorale témoigne de la vie quotidienne rurale de l’époque. Des femmes du village, vêtues de la robe traditionnelle et de foutas à rayures, marchent sur un sentier en portant des jarres et de grands paniers, tout en accompagnant un petit troupeau de moutons. Selon les précisions transmises par le contributeur, les jarres contiennent de l’eau et les paniers sont appelés « akechoual ».</p><ImageArchiveViewer src="/archives/vie-village/retour-des-champs-1966.jpg" alt="Photographie en noir et blanc de femmes portant des jarres et des paniers sur un chemin, aux côtés d’un troupeau de moutons" title="Retour des champs · photographie transmise" aspectRatio="720 / 951" /><p><strong>Tharkavthe, sur un chemin menant vers Aït Mesbah · janvier 1966.</strong> Date, localisation précise et identification de la scène comme un retour des champs transmises par le contributeur ; la source originale reste à retrouver.</p><p>Photographie trouvée sur Internet et transmise au site. Photographe, collection d’origine et droits de reproduction à identifier. Ce document est distinct du reportage photographique de 1939. Le contenu des jarres et le nom des paniers relèvent du témoignage transmis, et non de la seule observation de l’image.</p><Link className="craft-link" href="/histoire-memoire/archives/retour-des-champs-1966">Consulter la fiche de cette photographie <span aria-hidden="true">→</span></Link></section>}
  {metier === "poterie" && <section className="craft-sources"><p className="craft-label">Un objet, une trace</p><h2>Le nom du village dans une collection de Harvard.</h2><p>La notice d’un pichet du Peabody Museum transcrit la mention « Ait Mesbah » sur son étiquette. Ce repère ouvre une nouvelle piste documentaire, distincte des photographies de 1939.</p><ImageArchiveViewer src="/archives/peabody/notice-125189.jpg" alt="Notice du Peabody Museum présentant le pichet et son étiquette mentionnant Ait Mesbah" title="Le pichet dans le catalogue de Harvard" aspectRatio="1425 / 1177" /><p>Source : Peabody Museum of Archaeology & Ethnology, Harvard — notice 125189. Capture du 12 septembre 2026. Autorisation de reproduction non obtenue à ce jour.</p><Link className="craft-link" href="/histoire-memoire/archives/pichet-ait-mesbah-peabody">Découvrir le pichet et sa notice <span aria-hidden="true">→</span></Link></section>}
  <article className="craft-story">{craft.sections.map(([title,text],index)=><section id={`chapitre-${index+1}`} key={title}><div><p className="craft-label">0{index+1} · {craft.material}</p><h2>{title}</h2></div><p>{text}</p></section>)}<aside>Cette première présentation s’appuie sur les informations transmises pour le site. Les parcours, les techniques locales et les objets seront documentés avec les personnes concernées.</aside></article>
  {metier === "poterie" && <section className="craft-sources"><p className="craft-label">Repères documentaires</p><h2>Un décor à regarder, une origine à préciser.</h2><p>Une étude de la poterie modelée situe les Aït Douala dans une aire où se rencontrent fonds blancs, bandes brun-rouge et lignes brunes. Elle mentionne Aït Mesbah à propos des appellations de motifs, tout en soulignant les transitions entre styles régionaux. Ces rapprochements ne suffisent pas, à eux seuls, à attribuer une pièce au village.</p><p>Les bordures de ce site en proposent une interprétation graphique contemporaine. Elles ne reproduisent pas un objet identifié et ne revendiquent aucune signification symbolique traditionnelle.</p><ul><li><a href="https://alger-roi.fr/Alger/arts/pdf/12_poterie_kabyle_algerianiste101.pdf" target="_blank" rel="noreferrer">La poterie modelée d’Afrique du Nord — étude des styles de Kabylie (PDF)</a></li><li><a href="https://m.quaibranly.fr/fr/professionnels/expositions-itinerantes/ideqqi" target="_blank" rel="noreferrer">Ideqqi — exposition du musée du quai Branly–Jacques Chirac</a> : un éclairage plus large sur la poterie berbère en Algérie.</li></ul></section>}
  <section className="craft-invitation"><p className="craft-label">Transmettre à son tour</p><h2>Votre souvenir peut ouvrir un récit.</h2><p>Une photo, le nom d’une personne, une histoire d’atelier : partagez ce que vous connaissez. Les contributions seront relues avant publication.</p><Link className="craft-link" href="/contribuer">Proposer une contribution <span aria-hidden="true">↗</span></Link></section>
  <nav className="craft-related" aria-label="Autres savoir-faire">{crafts.filter(item=>item.slug!==metier).map(item=><Link href={`/artisanat/${item.slug}`} key={item.slug}>{item.name} <span aria-hidden="true">→</span></Link>)}</nav></main><SiteFooter/></>;
}
